### ISSUE TITLE
Pregnancy Tab

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#104]
For some reason preg rate data for 2015 DAU 9 WTD is missing. Can you check and see if it is on the code end? Heather says the data is in the database. Thanks!

**Comment by Huh** [comment]
The Unit entries are things like Brown, Sully and Black Hill.  I know those won't match anything.  

Several entries have Latitude, but no Longitude.  A few other entries are missing both coordinates.

The species column has Whitetail Deer and not White-tailed Deer for many of the entries.  This is true of all the DAU 9 entries.  ID takes values of 1904 to 1958 if that helps.

**Comment by gfrc11752** [comment]
Here is the data I pulled out of access for those brown whitetails. It appears they all should have a lat/long that assigns them to DAU 9. I will change the “Whitetail Deer” entries. That maybe are only problem.

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

3

NA

NA

Wiechmann

45.675697

-98.162598

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.675697

-98.162598

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.675697

-98.162598

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

1

NA

NA

Wiechmann

45.675697

-98.162598

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.675697

-98.162598

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.675697

-98.162598

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.675697

-98.162598

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.675697

-98.162598

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.675697

-98.162598

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.713528

-98.125257

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.713528

-98.125257

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.713528

-98.125257

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.713528

-98.125257

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.713528

-98.125257

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.713528

-98.125257

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

3

NA

NA

Wiechmann

45.713528

-98.125257

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.718174

-98.099102

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.718174

-98.099102

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.718174

-98.099102

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

1

NA

NA

Wiechmann

45.718174

-98.099102

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.718174

-98.099102

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.718174

-98.099102

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.718174

-98.099102

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.718174

-98.099102

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

3

NA

NA

Wiechmann

45.68081

-98.039294

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.68081

-98.039294

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.68081

-98.039294

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

1

NA

NA

Wiechmann

45.68081

-98.039294

NA

2015

02/22/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.68081

-98.039294

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.67695

-98.223667

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.67695

-98.223667

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.67695

-98.223667

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

1

NA

NA

Wiechmann

45.67695

-98.223667

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.67695

-98.223667

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

1

NA

NA

Wiechmann

45.67695

-98.223667

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.67695

-98.223667

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.777724

-98.14076

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.777724

-98.14076

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

3

NA

NA

Wiechmann

45.777724

-98.14076

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.777724

-98.14076

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.777724

-98.14076

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.777724

-98.14076

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.777724

-98.14076

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

3

NA

NA

Wiechmann

45.777724

-98.14076

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.77719

-98.082805

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.77719

-98.082805

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.77719

-98.082805

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.77719

-98.082805

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

0

NA

NA

Wiechmann

45.77719

-98.082805

NA

2015

02/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.77719

-98.082805

NA

2015

03/21/2015

4

Brown

Whitetail Deer

adult

NA

1

NA

NA

Wiechmann

45.7647333

-98.06205

NA

2015

03/21/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.7716

-98.060017

NA

2015

03/21/2015

4

Brown

Whitetail Deer

adult

NA

1

NA

NA

Wiechmann

45.6420333

-98.114967

NA

2015

03/21/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.6775

-98.140767

NA

2015

03/23/2015

4

Brown

Whitetail Deer

adult

NA

2

NA

NA

Wiechmann

45.7603

-98.16

NA

**Comment by Huh** [comment]
Yeah, all of the Brown 2015 entries are Whitetail Deer and so thrown out.  The Lat and Long are entered for all of the Brown entries and they produce points in Brown county.

One thing that is concerning is that the number decimal places in the Lat and Long columns keep changing.  This will move animals a bit when rounded too much.

Also, it looks like some of the Longitude values are positive, but most are negative.

Is there a reason why county is being used?

**Comment by gfrc11752** [comment]
No, we should not be using county, I will get this file cleaned up.

**Comment by Huh** [comment]
Ok, sounds good, thanks. Josh Nowak 

    On Monday, March 28, 2016 4:32 PM, gfrc11752 <notifications@github.com> wrote:
 

 No, we should not be using county, I will get this file cleaned up.

**Comment by Huh** [comment]
Looks like it is in there now (55 observations).  I will close, but feel free to open it back up if this is still an issue.
