### ISSUE TITLE
Server Connection Issues

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#106]
PopR keeps timing out, not sure if it is a server issue or what is going on?

**Comment by Huh** [comment]
What does timing out mean?  Does the screen turn gray?
I will look into it on my end. Josh Nowak 

    On Wednesday, March 30, 2016 10:10 AM, gfrc11752 <notifications@github.com> wrote:
 

 PopR keeps timing out, not sure if it is a server issue or what is going on?—

**Comment by gfrc11752** [comment]
Yep, screen turns gray, multiple users have mentioned the issue.

**Comment by Huh** [comment]
I can't seem to reproduce it on my end.  In terms of the server it is not working very hard at all.  I think we should give it a minute and see if the internet connection is the issue. Josh Nowak 

    On Wednesday, March 30, 2016 11:04 AM, gfrc11752 <notifications@github.com> wrote:
 

 Yep, screen turns gray, multiple users have mentioned the issue.

**Comment by gfrc11752** [comment]
Hasn’t occurred since I sent that message. Must have been in internet connection issue. I have been on the website all day trying to get a bunch of numbers crunched. We have our deer recommendation meetings next Tuesday so I am hoping we can get the IPM and other little things fixed up/modified by then.

**Comment by Huh** [comment]
Ok, thanks for letting me know the timeline.  I will get on as many of these things as I can. Josh Nowak 

    On Wednesday, March 30, 2016 12:45 PM, gfrc11752 <notifications@github.com> wrote:
 

 Hasn’t occurred since I sent that message. Must have been in internet connection issue. I have been on the website all day trying to get a bunch of numbers crunched. We have our deer recommendation meetings next Tuesday so I am hoping we can get the IPM and other little things fixed up/modified by then.

**Comment by gfrc11752** [comment]
You’re the man, thanks! The website definitely will be under a microscope the next couple of weeks.

**Comment by gfrc11752** [comment]
Really having connection issues again today. Got the gray screen 5 times in the last 20 minutes!!

**Comment by Huh** [comment]
I checked with our IT and there are no known issues with our connection, the server is healthy and the logs do not suggest any problems.  We have calls into some other folks and will report back if I discover anything.
Is it still happening?
For what it is worth, I was on all morning and did not get kicked off.  However, I will continue to look for problems as this is completely unacceptable.


Josh NowakUniversity of Montana

-------- Original message --------
