### ISSUE TITLE
Herd Composition Tab

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#107]
I am getting questions as to why/how the m:f ratios from the herd comp data are so high in PopR. Looking at individuals as the sampling unit we get around 25-30m/100f. PopR is consistently computing ratios between 40-50m/100 females using the group as the sample unit. Just further clarification as to how PopR calculates this statistic would be helpful. Thanks!

**Comment by Huh** [comment]
How are you calculating it that you get 25-30?  
I assume that is something like getting the ratio for each observation and then taking the mean?  If you could write out the math it might help me understand. Josh Nowak 

    On Wednesday, March 30, 2016 10:34 AM, gfrc11752 <notifications@github.com> wrote:
 

 I am getting questions as to why/how the m:f ratios from the herd comp data are so high in PopR. Looking at individuals as the sampling unit we get around 25-30m/100f. PopR is consistently computing ratios between 40-50m/100 females using the group as the sample unit. Just further clarification as to how PopR calculates this statistic would be helpful. Thanks!—

**Comment by gfrc11752** [comment]
Attached are the calculations I have been using for the last few years.

**Comment by Huh** [comment]
The primary difference is that, if I understand correctly, previous calculations were done using 

fawns/(fawns + does)

whereas we now consider something analogous to 

fawns/does

We actually are doing a two step process where we first describe the composition of the herd and then calculate the ratios.  For example...

```r
> fawns <- 40
> does <- 100
> bucks <- 33
> #  Then the proportion of the herd made up of each demographic is
> total <- fawns + does + bucks
> p_fawn <- fawns/total
> p_fawn
[1] 0.2312139
> p_doe <- does/total
> p_doe
[1] 0.5780347
> p_bucks <- bucks/total
> p_bucks
[1] 0.1907514
> #  The age and sex ratios we want are then calculated by
> p_fawn/p_doe
[1] 0.4
> p_bucks/p_doe
[1] 0.33

```

The important bit here for me is that we want some measure of reproduction and survival.  So, we have does giving birth and then fawns surviving in the numerator and the number of does from the spring that survived to be counted during the ratio estimates in the denominator.  Not sure why the does and fawns were added in the denominator, but I am open to ideas.

**Comment by gfrc11752** [comment]
We actually take the sum of all fawns observed and simply divide them by the total number of does observed.
fawns/does-- Region 1 Example 1334/1422= .94*100 – 94 fawns per 100 does

fawn_p 1334/3096 = 0.43
doe_p 1422/3096 = 0.459
buck_p 340/3096 = .109

fawn/doe: 0.43/0.459 =  .936 F:D
Same answer
.109/.459 = .237 B:D




# Fawns

# Does

# Bucks

Total

F:100D

B:100D















Region 1

1334

1422

340

3096

94

24

Region 2

849

1050

273

2172

81

26

Region 3

1485

1375

532

3392

108

39

Region 4

2156

2375

700

5231

91

29



To calculate CI’s I use the below equations

Binomial Confidence Interval used

p = a/n (the proportion of males)

where a = number of males; n = number of males + females


if 95% confidence limits then z = 1.96


Pu = (p+z^2/(2*n) + z*(SQRT((p*(1-p)/n)+(z^2/(4*n^2)))))/(1+z^2/n)

Pl = (p+z^2/(2*n) - z*(SQRT((p*(1-p)/n)+(z^2/(4*n^2)))))/(1+z^2/n)


Then:


Sex ratio = number of males/number of females = p/(1 - p)

Upper confidence limit = Pu/(1 - Pu)

Lower confidence limit = Pl/(1 - Pl)

**Comment by Huh** [comment]
Sorry, I was looking at the fawn prop column.  So, we are doing the same thing roughly.  Where is the discrepancy?  You mentioned one that was twice as big. Josh Nowak 

    On Wednesday, March 30, 2016 1:48 PM, gfrc11752 <notifications@github.com> wrote:
 

 We actually take the sum of all fawns observed and simply divide them by the total number of does observed.
fawns/does-- Region 1 Example 1334/1422= .94*100 – 94 fawns per 100 does

fawn_p 1334/3096 = 0.43
doe_p 1422/3096 = 0.459
buck_p 340/3096 = .109

fawn/doe: 0.43/0.459 = .936 F:D
Same answer
.109/.459 = .237 B:D




# Fawns

# Does

# Bucks

Total

F:100D

B:100D















Region 1

1334

1422

340

3096

94

24

Region 2

849

1050

273

2172

81

26

Region 3

1485

1375

532

3392

108

39

Region 4

2156

2375

700

5231

91

29



To calculate CI’s I use the below equations

Binomial Confidence Interval used

p = a/n (the proportion of males)

where a = number of males; n = number of males + females


if 95% confidence limits then z = 1.96


Pu = (p+z^2/(2*n) + z*(SQRT((p*(1-p)/n)+(z^2/(4*n^2)))))/(1+z^2/n)

Pl = (p+z^2/(2*n) - z*(SQRT((p*(1-p)/n)+(z^2/(4*n^2)))))/(1+z^2/n)


Then:


Sex ratio = number of males/number of females = p/(1 - p)

Upper confidence limit = Pu/(1 - Pu)

Lower confidence limit = Pl/(1 - Pl)

**Comment by gfrc11752** [comment]
I randomly selected a few stats to compare from the fall class analysis and popR, my biggest concern is with the m;f ratios.  See attached

**Comment by Huh** [comment]
Great, I will check these out and get back to you. Josh Nowak 

    On Wednesday, March 30, 2016 2:57 PM, gfrc11752 <notifications@github.com> wrote:
 

 I randomly selected a few stats to compare from the fall class analysis and popR, my biggest concern is with the m;f ratios. See attached

**Comment by Huh** [comment]
I think I have a fix and will implement it tomorrow after a bit of testing.  There was a problem with the choice of prior. Josh Nowak 

    On Wednesday, March 30, 2016 3:04 PM, Josh Nowak <Joshnwk@yahoo.com> wrote:
 

 Great, I will check these out and get back to you. Josh Nowak 

    On Wednesday, March 30, 2016 2:57 PM, gfrc11752 <notifications@github.com> wrote:
 

 I randomly selected a few stats to compare from the fall class analysis and popR, my biggest concern is with the m;f ratios. See attached

**Comment by gfrc11752** [comment]
Sounds good, thanks!

**Comment by Huh** [comment]
The prior is now fixed and a new version of the tab is live.  The estimates are almost exactly what you got in the few test cases I did.  The models also got a lot faster.

Please close if you agree that things look good.

**Comment by gfrc11752** [comment]
Awesome!
