### ISSUE TITLE
Remove repeated columns from survival database

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#11]
The age and frequency columns are both repeated in the copy of the master file.  The function I wrote to mimic the database and other data cannot contain repeated column names and so cannot match the input.

**Comment by gfrc11752** [comment]
Alight, I will see what I can do but right now I am having a heck of a time merging the capture, monitoring and mortality databases into one table without a manual export and join.

**Comment by Huh** [comment]
It is just a placeholder for us.  You find the best workflow for you and we will go from there. Josh Nowak 


     On Friday, July 17, 2015 1:47 PM, gfrc11752 <notifications@github.com> wrote:
   

 Alight, I will see what I can do but right now I am having a heck of a time merging the capture, monitoring and mortality databases into one table without a manual export and join. —

**Comment by Huh** [comment]
Is this fixed now?  I think it is....
