### ISSUE TITLE
Pregnancy Tab

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#110]
I added a method column into the Pregnancy rate table. If you could make sure that appears in the raw data table in PopR that would be great. 

Column Headers:
Year 	Date 	Region	Unit	Species	Ageclass	Age	Fetus_Count	Female_Count 	Male_Count	Observer	Latitude	Longitude 	DAU	   Method	  PrimaryID

**Comment by Huh** [comment]
Done
