### ISSUE TITLE
Survival raw data tab

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#117]
Not a big deal, but when we recaptured a few adult bucks in DAU 9 it is still showing the old frequency from the first capture record. Any chance you could pull just the frequency form the 2nd capture record for that unique ID to display the most current frequency in the raw data table?

**Comment by Huh** [comment]
Yes sir, I was pulling the first entry to make sure that values were unique, but I will pull the last that is not NA. Josh Nowak 

    On Wednesday, April 13, 2016 9:48 AM, gfrc11752 <notifications@github.com> wrote:
 

 Not a big deal, but when we recaptured a few adult bucks in DAU 9 it is still showing the old frequency from the first capture record. Any chance you could pull just the frequency form the 2nd capture record for that unique ID to display the most current frequency in the raw data table?—
