### ISSUE TITLE
Survival Calculation Issue

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#125]
I believe we are getting erroneous survival estimates for the following DAU.

Mule Deer, DAU 4, 2016, Fawn

It is giving us a 12% survival estimate for July. Something isn't right here...

**Comment by paul-lukacs** [comment]
Most of the fate dates for fawns are in mid-July (7/13/2016).  Those animals would not be included in the July estimate until the end of the month.  When was the most recent flight and have those data been stored in the database?

Paul

**Comment by gfrc11752** [comment]
Yeah, I just noticed only the ones that died were entered in on Aug 3 and 4th. The monitoring records for everything else should be entered today. Good catch, thanks Paul.
