### ISSUE TITLE
Missing Data - Age-class Misclassification?

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#127]
We are currently missing all of the fawns from 2016. 

A few examples: MD, DAU 3: 2016321002, 2016321038
WTD, DAU 3: 2016311001, 2016311031
MD, DAU 4: 2016421001
I searched the entire database and found 5 WTD fawns in 2016 in DAU 11

I find it strange as well that juveniles are missing in 2015 DAU 3.

**Comment by gfrc11752** [comment]
It was a sequel database issue....I have resolved the issue.

**Comment by Huh** [comment]
Great, thanks for looking into that! Josh Nowak 

    On Thursday, September 29, 2016 1:06 PM, gfrc11752 <notifications@github.com> wrote:
 

 It was a sequel database issue....I have resolved the issue. —
