### ISSUE TITLE
Composition Unit Entries

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#13]
Composition data also has entries of BH2 and BH3.  These entries occur in 2011 and 2014, but only BH1 is a recognized unit per the shapefiles.  In short, the data do not agree, these are either bad entries or the shapefiles are missing units.

**Comment by gfrc11752** [comment]
These should include BH2 and 3 but should be called BD1-4.

**Comment by gfrc11752** [comment]
Did you get the attachments?
