### ISSUE TITLE
Website keeps crashing

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#130]
After I load the survival data, white-tailed deer, DAU 9, 2016 juveniles the website gives me a java script error. Any thoughts/suggestions?

Thanks!

**Comment by Huh** [comment]
Yeah, I just updated a whole bunch of stuff, so this is not completely unexpected.  I will look into it now. Josh Nowak 

    On Thursday, November 3, 2016 12:53 PM, gfrc11752 <notifications@github.com> wrote:
 

 After I load the survival data, white-tailed deer, DAU 9, 2016 juveniles the website gives me a java script error. Any thoughts/suggestions?Thanks!—

**Comment by gfrc11752** [comment]
Thanks!

**Comment by Huh** [comment]
This message is probably best viewed on [GitHub](https://github.com/Huh/PopR_SDGFP/issues/130)

A few observations...

The following animals do not have an entry for sex
```r
2015221027
2015311028
2015511027
2015711002
```

The following animals do not have a DAU assigned to them, but they do have coordinates and that should have been sufficient.  I will look into why these coordinates were not used, it may be that they are bad coordinates.
```r
2014511001
2016311006
```
For the following 23 animals a fate could not be determined.  These animals are neither dead nor alive according to the code. I spot checked a few of the Species by Year by DAU combinations and it looks to me like these animals are causing problems.
```r
2012123067
2012123068
2012123069
2013121002
2013121007
2013121010
2013121011
2014511001
20161111033
20161112007
20161112010
20161112011
20161113009
20161113013
2016313076
2016423003
2016423038
2016623009
2016623021
2016623047
2016911037
2016913083
2016913094
```

At least some of these animals have NA status for the last several monitoring occasions.  For example...

```r
> tmp_sp %>% filter(ID == "2016913083") %>% data.frame
           ID Frequency           Species Month BioYear Unit DAU CapAge Age Ageclass  Sex    CapDate       Date Status            Fate Monitored Censored  Dead Latitude Longitude Region
1  2016913083   151.643 White-tailed Deer     3    2016  47A   9      3   3    Adult Male 2016-02-26 2016-02-26      1           alive      TRUE    FALSE FALSE 45.79824 -99.59354      4
2  2016913083   151.643 White-tailed Deer     3    2016  47A   9      3   3    Adult Male 2016-02-26 2016-03-07     NA            <NA>      TRUE    FALSE FALSE       NA        NA      4
3  2016913083   151.643 White-tailed Deer     3    2016  47A   9      3   3    Adult Male 2016-02-26 2016-03-14      1           alive      TRUE    FALSE FALSE       NA        NA      4
4  2016913083   151.643 White-tailed Deer     4    2016  47A   9      3   3    Adult Male 2016-02-26 2016-04-15      1           alive      TRUE    FALSE FALSE       NA        NA      4
5  2016913083   151.643 White-tailed Deer     6    2016  47A   9      3   3    Adult Male 2016-02-26 2016-05-17      1           alive      TRUE    FALSE FALSE       NA        NA      4
6  2016913083   151.643 White-tailed Deer     6    2016  47A   9      3   3    Adult Male 2016-02-26 2016-06-08      1           alive      TRUE    FALSE FALSE       NA        NA      4
7  2016913083   151.643 White-tailed Deer     7    2016  47A   9      3   3    Adult Male 2016-02-26 2016-07-15      1           alive      TRUE    FALSE FALSE       NA        NA      4
8  2016913083   151.643 White-tailed Deer     8    2016  47A   9      3   3    Adult Male 2016-02-26 2016-08-04      1           alive      TRUE    FALSE FALSE       NA        NA      4
9  2016913083   151.643 White-tailed Deer    10    2017  47A   9      3   3    Adult Male 2016-02-26 2016-09-19     NA           alive      TRUE    FALSE FALSE       NA        NA      4
10 2016913083   151.643 White-tailed Deer    10    2017  47A   9      3   3    Adult Male 2016-02-26 2016-09-19     NA Collar Tore Off      TRUE     TRUE FALSE 45.69687 -98.64235      4
> tmp_sp %>% filter(ID == "2016423003") %>% data.frame
          ID Frequency   Species Month BioYear Unit DAU CapAge Age Ageclass    Sex    CapDate       Date Status  Fate Monitored Censored  Dead Latitude Longitude Region
1 2016423003   149.635 Mule Deer     4    2016  21A   4      3   3    Adult Female 2016-03-19 2016-03-19      1 alive      TRUE    FALSE FALSE 43.71609 -103.1486      1
2 2016423003   149.635 Mule Deer     4    2016  21A   4      3   3    Adult Female 2016-03-19 2016-03-29     NA  <NA>      TRUE    FALSE FALSE       NA        NA      1
3 2016423003   149.635 Mule Deer     4    2016  21A   4      3   3    Adult Female 2016-03-19 2016-04-06     NA alive      TRUE    FALSE FALSE       NA        NA      1
4 2016423003   149.635 Mule Deer     5    2016  21A   4      3   3    Adult Female 2016-03-19 2016-05-06     NA alive      TRUE    FALSE FALSE       NA        NA      1
5 2016423003   149.635 Mule Deer     6    2016  21A   4      3   3    Adult Female 2016-03-19 2016-06-03     NA alive      TRUE    FALSE FALSE       NA        NA      1
6 2016423003   149.635 Mule Deer     7    2016  21A   4      3   3    Adult Female 2016-03-19 2016-07-13     NA alive      TRUE    FALSE FALSE       NA        NA      1
7 2016423003   149.635 Mule Deer     9    2016  21A   4      3   3    Adult Female 2016-03-19 2016-09-06     NA alive      TRUE    FALSE FALSE       NA        NA      1
8 2016423003   149.635 Mule Deer    11    2017  21A   4      3   3    Adult Female 2016-03-19 2016-10-17     NA alive      TRUE    FALSE FALSE       NA        NA      1

``` 

Can you fix the status column and then try again?  I suspect that is the issue although I can't seem to reproduce it on my end.  The recent updates have made the workflow a little more robust to these types of errors.  

Josh

**Comment by gfrc11752** [comment]
Yes, I will dive right into this and see what I come up with. Thanks for checking it out so quickly.

**Comment by gfrc11752** [comment]
Of the 23 I only needed to make a few changes regarding the status column, otherwise they all had a 1, 2 or 3. An example: 2016913083 had an NA in the status column in the mortality record when the collar tore off, I replaced with a 1.

I reloaded the data into PopR and still no luck, I am getting the same error message.

**Comment by Huh** [comment]
OK, I will keep looking.
Josh 
 
  On Thu, Nov 3, 2016 at 3:37 PM, gfrc11752<notifications@github.com> wrote:   Of the 23 I only needed to make a few changes regarding the status column, otherwise they all had a 1, 2 or 3. An example: 2016913083 had an NA in the status column in the mortality record when the collar tore off, I replaced with a 1.

I reloaded the data into PopR and still no luck, I am getting the same error message.

**Comment by gfrc11752** [comment]
Josh, website is still crashing? Did you have a chance to dig further yet?

**Comment by Huh** [comment]
I am aware that nothing has been fixed.  I am working on a total update that includes your new IPM page.  I will take one more look at the data this afternoon though to see if there is something obvious that I missed. Josh Nowak 

    On Tuesday, November 8, 2016 11:09 AM, gfrc11752 <notifications@github.com> wrote:
 

 Josh, website is still crashing? Did you have a chance to dig further yet?—

**Comment by Huh** [comment]
In the meantime if you need any numbers I run the models on my computer. Josh Nowak 

    On Tuesday, November 8, 2016 12:33 PM, Josh Nowak <Joshnwk@yahoo.com> wrote:
 

 I am aware that nothing has been fixed.  I am working on a total update that includes your new IPM page.  I will take one more look at the data this afternoon though to see if there is something obvious that I missed. Josh Nowak 

    On Tuesday, November 8, 2016 11:09 AM, gfrc11752 <notifications@github.com> wrote:
 

 Josh, website is still crashing? Did you have a chance to dig further yet?—

**Comment by gfrc11752** [comment]
Nothing urgent, thanks for your continued efforts on this project. Much appreciated!!

**Comment by Huh** [comment]
I finally got some debugging information from the site and found the spot where the code was broken by a package update.  The change has been made, but I have not extensively tested the site.  Please let me know of any other errors that occur. I ran a single model and played with the setup UI and everything functioned well.
Josh 

    On Tuesday, November 8, 2016 12:39 PM, gfrc11752 <notifications@github.com> wrote:
 

 Nothing urgent, thanks for your continued efforts on this project. Much appreciated!!

**Comment by gfrc11752** [comment]
Awesome! The survival tab is now working. Thanks!
