### ISSUE TITLE
Data check error

### ISSUE THREAD

**Issue by 12382** [Huh/PopR_SDGFP#131]
I was going to check the survival data for any errors, and when I clicked "Run Check" this error popped up.

Error: no applicable method for 'filter_' applied to an object of class "NULL"

Let me know if there is something I need to do on my end to clean up data in order to avoid this error.

Thanks,
Lauren

**Comment by 12382** [comment]
Sorry, I guess I need to get data before I can run a check.  My bad.

**Comment by Huh** [comment]
Lauren,

It has been a few days and I wanted to check in to make sure everything was still working as expected.  If everything is good I will close this issue, but wanted to check with you first.

Thanks for using the issue tracker!

Josh

**Comment by 12382** [comment]
Yes, everything is good.  Mistake on my part, and I realized it minutes after sending the report.  Sorry.

Lauren Wiechmann |  Resource Biologist
South Dakota Game, Fish and Parks
4130 Adventure Trail | Rapid City, SD 57702
605.394.2382| lauren.wiechmann@state.sd.us<mailto:lauren.wiechmann@state.sd.us>



[cid:image002.jpg@01D25483.6C734BB0]<http://gfp.sd.gov/agency/social-media.aspx>
