### ISSUE TITLE
Herd Composition

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#133]
41A is being summarized in the wrong DAU. It should be in DAU 4 not 7.

Also, 30AB data is not being read by PopR, thus we are missing records. This unit would be in DAU 7.

**Comment by Huh** [comment]
The DAU tab suggests that 41A is in DAU 7, but you can change that if you want.  Just fit a new cluster model and modify the table as you see fit.  This may be the result of an update, but I have tried hard not to change this file.

I am looking at 30AB now.

**Comment by Huh** [comment]
30AB is being picked up just fine, but in the data the Species is entered incorrectly.

```r
   PrimaryID Year       Date Region Unit           Species         Latitude
1      71094 2012 09/20/2012      2 30AB         Mule Deer     43.406533333
2      71099 2012 09/23/2012      2 30AB White-tailed Deer     43.248773333
3      71308 2012 09/23/2012      2 30AB White-tailed Deer     43.293041667
4      71309 2012 09/23/2012      2 30AB White-tailed Deer     43.295073333
5      71310 2012 09/23/2012      2 30AB White-tailed Deer     43.300488333
6      71354 2012 09/26/2012      2 30AB White-tailed Deer     43.371923333
7      71857 2014 10/30/2014      2 30AB    Whitetail Deer     43.241256667
8      71984 2014 09/18/2014      2 30AB    Whitetail Deer     43.206831667
9      72494 2014 10/30/2014      2 30AB    Whitetail Deer        43.067775
```

Change Whitetail Deer to White-tailed Deer and everything should be fine.  

When you said it was not picking it up I assume you mean that you were missing some data, but not all, correct?  I can see a handful of entries for 2016 using several different setup configurations.

**Comment by gfrc11752** [comment]
Correct, will do.
