### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#15]
Regarding the herd composition data, being that the group is the sample what do you do with groups that are just bucks. How do you formulate a ratio for a group if all you see is 5 bucks, 0 does? Thanks!

**Comment by paul-lukacs** [comment]
The group level estimate for ratio data is:

Bucks/(Bucks+Does)

Therefore, if there are 5 bucks and 0 does, the group estimate is 5/(5+0).  We work in proportions for estimation and then convert to bucks:100 does for the final output.

Paul

**Comment by gfrc11752** [comment]
Sounds good, thanks!

**Comment by Huh** [comment]
Retooled this analysis, it is now a multinomial and the ratio estimates are derived parameters.  The analysis considers data at the group level.
