### ISSUE TITLE
Add MortSigHeard column to survival data merge fun

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#19]

**Comment by Huh** [comment]
Done, let me know if it does not match the database in some way!  Please close this issue when you are satisfied that everything is correct.

**Comment by gfrc11752** [comment]
Will do thanks.

**Comment by gfrc11752** [comment]
Script is not working correctly, Error message 

Error in `$<-.data.frame`(`*tmp*`, "Cause_of_Death", value = c(NA, NA,  : 
  replacement has 57 rows, data has 58
In addition: Warning messages:
1: In is.na(cod) : is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(cod) : is.na() applied to non-(list or vector) of type 'NULL'

It is something to do with the COD not converting to the Fate field name. Also Id, should be Id1.

**Comment by Huh** [comment]
If you would like to email me the problem data I would be happy to take a look.

**Comment by gfrc11752** [comment]
Try this one for starters….

**Comment by Huh** [comment]
GitHub stripped the attachment, can you email it please.

**Comment by Huh** [comment]
Any chance you can resend the email to Joshnwk@gmail.com?  Yahoo's server is hosed and I had enough computer problems today that I just switched machines for good.....these computer issues are getting old.

**Comment by Huh** [comment]
In the data who is you and me?  Who's on first?  Anyway, you want me to make the data look like the top one or the bottom?  I am thinking bottom, but want confirmation...

**Comment by gfrc11752** [comment]
My Data = Kristin Sternhagen (Cybertracker database person), Your Data = R generated files. I need you to make the R script generate the top field names. The top field names are what is coming through the API connection (Date is being changed to mm/dd/yyyy).

**Comment by Huh** [comment]
Ok, give it a whirl.  The latest version is on GitHub now.  Don't forget to hit the raw button before copying it.

**Comment by gfrc11752** [comment]
Yahtzee!! Good work, things are rockin!

**Comment by Huh** [comment]
Dope! Josh Nowak 


     On Tuesday, August 4, 2015 8:24 AM, gfrc11752 <notifications@github.com> wrote:
   

 Closed #19.—
