### ISSUE TITLE
Encounter History Survival Data Handling Failure

### ISSUE THREAD

**Issue by 12382** [Huh/PopR_SDGFP#196]
I am trying to download the data for the Survival tab.  When I select any combination of species, DAU, Age, Sex, and time range I receive an error message "A problem was encountered when building encounter histories.  Survival data handling failure."  This was working fine this morning, so I'm not sure what changed.  It seems as if the survival data is working fine within the IPM.

**Comment by Huh** [comment]
I am receiving some data for which we are failing to calculate a final observation date.  For an example see animal `20171112001`

```R
  ID          LastHeard  LastListen MissingSince MortDate   LastIsMort Last       Fate  MortRecord Latitude Longitude
  <chr>       <date>     <date>     <time>       <date>     <lgl>      <date>     <chr> <lgl>         <dbl>     <dbl>
1 20171112001 NA         2017-01-28 Inf          NA         NA         NA         <NA>  FALSE            NA        NA
```

I am tracking down the source of this problem now and will update shortly

**Comment by Huh** [comment]
Looks like this animal only has a single row of data

```R
  ID          Frequency Species           Date       Month BioYear DAU   Unit  Ageclass Sex   Status Fate  Censored Dead  MortSigHeard CollectionType Latitude Longitude
  <chr>       <chr>     <chr>             <date>     <int>   <int> <chr> <chr> <chr>    <chr>  <int> <chr> <lgl>    <lgl> <lgl>        <chr>             <dbl>     <dbl>
1 20171112001 152.481   White-tailed Deer 2017-01-28     1    2017 DAU11 <NA>  J        M         NA <NA>  FALSE    FALSE FALSE        Deer Capture       44.3     -97.0
```

**Comment by Huh** [comment]
The issue is that Status is NA despite it being a capture record.  This shouldn't be possible in terms of data entry.

```R
  ID          Frequency Date       Month BioYear Region   DAU Unit  Ageclass Sex   Status Fate  Censored Dead  MortSigHeard CollectionType Species           Latitude Longitude
  <chr>       <chr>     <date>     <int>   <int>  <int> <dbl> <chr> <chr>    <chr>  <int> <chr> <lgl>    <lgl> <lgl>        <chr>          <chr>                <dbl>     <dbl>
1 20171112001 152.481   2017-01-28     1    2017      3    11 06A   J        M         NA <NA>  FALSE    FALSE FALSE        Deer Capture   White-tailed Deer     44.3     -97.0
```

I will email the list of 570 animals for which this is an issue.  Last night I also found duplicate records for the first time, which may be related given that lots of tinkering has been going on with the API.

**Comment by Huh** [comment]
Another example, but this time it was monitored once

```R
> survd %>% filter(ID1 == "2017912054") %>% data.frame
  PrimaryID                                   ID                 Date1           Species        ID1 Frequency Status Fate MortSigHeard Capture_Unit Monitoring_Unit AgeClass  Sex  Age Censored Dead Fate_Unit Weight HoofGrowth
1   1328848 5282c950-02f5-4c29-8813-19519d89fffa 1/24/2017 12:00:00 AM White-tailed Deer 2017912054   152.991   <NA> <NA>         <NA>         <NA>            <NA> juvenile    F <NA>     <NA> <NA>      <NA>   <NA>       <NA>
2   1333226                                 1687 2/10/2017 12:00:00 AM White-tailed Deer 2017912054   152.991  Alive <NA>         <NA>         <NA>            <NA>     <NA> <NA> <NA>     <NA> <NA>      <NA>   <NA>       <NA>
      Observer   DAU DeathEvidence Comments Latitude Longitude  CollectionType    Source
1 SteveGriffin  DAU9          <NA>     <NA> 45.21968 -99.15364    Deer Capture Survey123
2   Nick Markl DAU 9          <NA>     <NA>     9999      9999 Deer Monitoring Survey123
```

**Comment by 12382** [comment]
This is really odd, since 20171112001 has a capture record in the collar database with Status 1, Fate Alive, Censored False, Dead False and 23 total records ending in a Collar Tore Off on 10/2/18.

2017912054 also shows 22 records with a correct capture record and ending in an alive record on 10/10/18.

Something is getting lost in translation.  Do I need to bring this to the attention of our IT Department, or can you tell if it is on their end or not?

Thanks for digging into this.

Lauren Wiechmann | Wildlife Biologist
South Dakota Game, Fish and Parks
4130 Adveture Trail | Rapid City, SD 57702
605.394.2382 | Lauren.Wiechmann@state.sd.us<mailto:Shuree.Mortenson@state.sd.us>
[Social_Orange2018]<gfp.sd.gov>

**Comment by Huh** [comment]
I am guessing the issue is on their end.  Ben has been working on the API the last few days to try and get the harvest data right and yesterday I found duplicate records for the first time and today we have this issue.  It all feels like something is changing, but I don't actually know the answer.

**Comment by 12382** [comment]
Too many new fingers in the pot.  There are more changes coming to the Collar Database.  I am hoping it will not affect the API or the Animal History encounters table, but let me know if you see issues occurring.  I wish I could make it to the meeting next week, but I will have to attend through Skype.  See you then.

Lauren Wiechmann | Wildlife Biologist
South Dakota Game, Fish and Parks
4130 Adveture Trail | Rapid City, SD 57702
605.394.2382 | Lauren.Wiechmann@state.sd.us<mailto:Shuree.Mortenson@state.sd.us>
[Social_Orange2018]<gfp.sd.gov>

**Comment by Huh** [comment]
Bummer, wish you could make it.

Thanks for the heads up.  Well, we will keep plugging away and hopefully
good things happen.

Thanks for the help Lauren,

Josh




[image: speedgoat logo] <http://www.speedgoat.io/>
*Josh Nowak*, President
*Speedgoat Wildlife Solutions*
(406) 214-7666

   - [image: Check out my work on Github!] <https://github.com/Huh>
   - [image: Connect with me on LinkedIn!]
   <https://www.linkedin.com/in/josh-nowak-speedgoat/>
