### ISSUE TITLE
YOY DAU 3 check that 2017-2018 animals available

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#203]
Survival
WTD
DAU 3
YOY
All Sex

2007-2018

Only returns 2015-2016 animals

**Comment by Huh** [comment]
MD and WTD neonate data missing statewide

I have internet issues where I can't quite verify this at the moment, but I will shortly.  Any input you may have would be appreciated, thanks.

@12382

**Comment by 12382** [comment]
I have a request in to BIT to make sure the API is functioning correctly for these recent years.  I wonder if this is linked to the examples we discussed earlier (2017912054 and 20171112001) that only showed a capture record with NA in the status, Fate, Censored and Dead fields.  The rest of their monitoring records just didn't make it to the API somehow.

**Comment by Huh** [comment]
I still don't see any captures after 2016 for this example.  Were animals captured in DAU3 after 2016?

The ID1 column now aligns with ID in all PopR data.  I hope this resolves the difficulties with looking things up.

**Comment by Huh** [comment]
I bet I was looking at old data.  When I updated the site I pushed an older data file to the server and I bet I was staring at that data, my fault.  Thanks for checking on this and teaching me how to use the tool=)
