### ISSUE TITLE
Try to update database to produce 2017 and 2018 data

### ISSUE THREAD

**Issue by 12382** [Huh/PopR_SDGFP#213]
Josh,

BIT has updated their GF104 database that feeds the API to include current data up to 11/3/18.  I am only seeing the total number of captured deer bar graph running to a September summary, not Oct or Nov.  I am also not seeing any 2018 captured animals in PopR "Encounter History" tab.  I am wondering if one of the tables in this GF104 database needs to be updated to get these 2018 records to be included in the analysis.  I am wondering if PopR is unable to read capture records for 2018 (either they are missing from a table or not formatted incorrectly).  
I see that the "Raw Data" tab in PopR has data from October 2018, so it is coming through the API.  I'm just not able to search for Animal IDs that start with 2018 in the "Raw Data" tab because the ID numbers used in the "Raw Data" tab don't include this ID 1 column that includes the Animal ID (would be nice if it did, hint hint).  Please let me know if you can diagnose anything that BIT can do to help get these final records into PopR correctly.
Thanks

**Comment by Huh** [comment]
This is on my to do list.  As a first step though, the website says the
last download was on 11/09, is this after the changes were made?




[image: speedgoat logo] <http://www.speedgoat.io/>
*Josh Nowak*, President
*Speedgoat Wildlife Solutions*
(406) 214-7666

   - [image: Check out my work on Github!] <https://github.com/Huh>
   - [image: Connect with me on LinkedIn!]
   <https://www.linkedin.com/in/josh-nowak-speedgoat/>

**Comment by 12382** [comment]
I believe this download was after the new recent data was added to the GF104 database.  They updated the records on 11/8/18.

Lauren Wiechmann | Wildlife Biologist
South Dakota Game, Fish and Parks
4130 Adveture Trail | Rapid City, SD 57702
605.394.2382 | Lauren.Wiechmann@state.sd.us<mailto:Shuree.Mortenson@state.sd.us>
[Social_Orange2018]<gfp.sd.gov>

**Comment by 12382** [comment]
Have you made any progress on this?  I still see the download of Survival data ending with September samples.  Still no samples displayed in October 2018.

**Comment by Huh** [comment]
I think the bar graph is using the biological year and that ends in September of 2018, we would need the slider to go to 2019 in order to pick up the data after that.  Not sure I like this.  The real problem in my opinion is that we have the slider ending at 2018, but in reality it should now say 2019 because we are subsetting the data based on bioyear and not on calendar year.  I will change the algo for the slider and see if that fixes things up a bit.

**Comment by Huh** [comment]
This is now fixed.  I am going to close this issue, but if you don't like the solution please reopen and let me know what I did wrong.

Thanks

**Comment by Huh** [comment]
See #218 b/c of the relationship with the covariate selection we need to set the slider to less than the last data available some times.  If you can't see the whole plot, like in the months of Oct, Nov and Dec (as this is the only time the slider won't be at the max) then just move the slider to see the last bits of data available.

I just wanted to make sure this functionality was clear.

@12382
