### ISSUE TITLE
slow run time and still disconnecting

### ISSUE THREAD

**Issue by lindbloom** [Huh/PopR_SDGFP#221]
Seems to be taking a longer than normal time to run a survival model.  I did a short run today with about 10,000 iterations I believe and after 2 hours I left.  I came back and it had disconnected me from server again.

Andrew has also been running a couple models all day as well, I think 20k iterations, and they still aren't done either.

**Comment by Huh** [comment]
Are they multi-state?  Are you using the whole state's worth of data?  Some
of them do take a long time to run.  This is one of the biggest arguments
for moving to a dashboard and the end user not actually running the models.

I don't think anything is wrong, but if you a notion that something is not
working I am open to ideas.

**Comment by lindbloom** [comment]
We will try some shorter runs today and get back to you.  We both got disconnected yesterday regardless, so that is an issue that still needs fixed

**Comment by Huh** [comment]
If it relates to an error with the model run I need to know the model you
ran.  I will check the timeout settings on the server too.

**Comment by Huh** [comment]
Closing in favor of #225
