### ISSUE TITLE
survival modeling error

### ISSUE THREAD

**Issue by lindbloom** [Huh/PopR_SDGFP#222]
Keep getting Survival Modeling Error message.   WTD, all years, all sexes, J, Multistate, WSI, sexes same, time monthly (tried constant too), space DAU.

**Comment by Huh** [comment]
Ok, I will take a look during my lunch break.  Have Lauren and BIT made
progress updating the animals with wonky data?




[image: speedgoat logo] <http://www.speedgoat.io/>
*Josh Nowak*, President
*Speedgoat Wildlife Solutions*
(406) 214-7666

   - [image: Check out my work on Github!] <https://github.com/Huh>
   - [image: Connect with me on LinkedIn!]
   <https://www.linkedin.com/in/josh-nowak-speedgoat/>

**Comment by Huh** [comment]
@12382 how are the data fixes coming?  Any word?

**Comment by 12382** [comment]
BIT was working on the issues.  When I download the data now I only get 9 deer with multiple mortalities rather than 31.  SO some of these have been corrected in GF104.  I will get an update about the rest of the issues hopefully today.

Lauren Wiechmann | Wildlife Biologist
South Dakota Game, Fish and Parks
4130 Adveture Trail | Rapid City, SD 57702
605.394.2382 | Lauren.Wiechmann@state.sd.us<mailto:Shuree.Mortenson@state.sd.us>
[Social_Orange2018]<gfp.sd.gov>

**Comment by 12382** [comment]
Corrections should be complete by this afternoon.

Lauren Wiechmann | Wildlife Biologist
South Dakota Game, Fish and Parks
4130 Adveture Trail | Rapid City, SD 57702
605.394.2382 | Lauren.Wiechmann@state.sd.us<mailto:Shuree.Mortenson@state.sd.us>
[Social_Orange2018]<gfp.sd.gov>

**Comment by lindbloom** [comment]
Looks like there are still 11 animals with some data issues.  Is this causing the error messages I keep getting and resulting inability to run much for survival analyses?  This morning I was able to start a mule deer run with adults, but when I opened up a second window to run additional analyses it keeps giving me the survival modeling error message.  Maybe that helps...

**Comment by lindbloom** [comment]
seems like it might be a multiple windows or tabs issue.  I started one survival run on adult wtd this morning, and when I tried juvs on another window it gave me the error message.  I went back and changed the model setup to the exact same as the first window which is still running successfully so far, but it immediately gave me the error.

**Comment by lindbloom** [comment]
Got multiple windows running now.  I think the problem may have been that I just clicked the box to use the last downloaded data, but didn't click the big download data button....  didn't think I had to do both.  Anyhow, I have 10 models running and Andrew has 8 running now, and we reached the "configured connection limit reached" message.  Someone else somewhere in the state must have the browser opened up I'd guess....

**Comment by Huh** [comment]
For my reference error log  SD_dev-shiny-20181129-083948-41057.log suggests a segfault, which may be related to dplyr issue https://github.com/tidyverse/dplyr/issues/322

In the hopes of resolving this issue I am going to reinstall some packages, fingers crossed.  I can't seem to recreate this segfault and so we may need to let it happen another time or two to gather more evidence about its origins.

**Comment by Huh** [comment]
I ran this model tonight and everything went fine for a short run.  I am going to close this issue and refer future conversation to issue #225
