### ISSUE TITLE
Different Output from Known Fates and Multi-state

### ISSUE THREAD

**Issue by nort0160** [Huh/PopR_SDGFP#224]
Just a quick comment irt output table. It looks as though known fate and multi-state model types output different results tables when data from both sexes are used and sexes are modeled as constant. The known fates model only includes results from one sex (F), and the multi-state options includes results with a row for both male and female (point estimates are the same for each row since sex was constant).

When the constant sexes model option is chosen with both sexes used, is there the possibility to include a value of 'both' in the sex column? If not, it might be better to have both included, even though the estimates are the same? I assume down the road there could be some sort of summary document that describes when data were downloaded, the subset that was used, and the model structure with run time?

One last quick note, Andy and I each ran the same 8 models last night (MD Ad, WTD ad, MD Juv, WTD Juv each cohort using the multi-state and known fates options). They all ran well with the exception of WTD Ad known fates (both disconnected from server). Although possible, it seems this coincidence wasn't random. I initially thought it was because we have the most data for adult WTD, but then if that were the case the multi-state WTD Ad model should have crashed too, since that presumably takes longer to iterate? I was able to get the model to successfully run this morning.

The model specifics were:
Spp=WTD; DAU=All; Sex=All; Age=A; Yrs=07-18; Model=KF; Cov=WSI; Cens=None; Sex Mod=Diff; Time Mod=Mo; Space Mod=DAU; NB/NI=15k/25k; Start time~4:30 pm 12/07

**Comment by Huh** [comment]
I am going to close this issue because we have resolved the unique line for each sex and the server issue has been moved to its own issue #225
