### ISSUE TITLE
Date and time stamp for "Use Last Download" changes when a new browser is opened

### ISSUE THREAD

**Issue by nort0160** [Huh/PopR_SDGFP#227]
Andy and I were both noticing that the date and time stamp specified by the check box "Use Last Download" would periodically change when we opened additional windows and clicked on the setup tab in the survival module. Sometimes it would be an earlier date/time, sometimes it would appear to be the most recent download. There did not appear to be a pattern to the date/time that was displayed.

**Comment by Huh** [comment]
That is weird.  I know it would have changed when you first looked at it because the file came from my computer and was changed when updated.  The date and time are simply read from the file system and not really under my control.  It is possible that if you had a connection the value was not updated immediately.  I will look at when it is updated/how often the date is update.

**Comment by Huh** [comment]
The file date-time is printed from the file that existed when the application was opened.  The file is not monitored for changes while the connection is open.

I can reproduce this behavior and adapt to what you may have seen and it fits with how it should behave.  For example, I downloaded a new set of data tonight.  When the download finished the date-time did not change.  I then opened a new tab in my browser (which caused an initial opening of the application) and the date-time updated to the download that just occurred.

How would you like this to behave going forward?  Do you want the application to listen to the date-time of the file and update when it changes?  I will implement that now.  If you want it changed to something else just holler.

**Comment by Huh** [comment]
Updates are now pushed to the server.

One thing to keep in mind is that you and every other user of SD applications are working from the same data.  So, if Andy downloads new data and then you open a new tab in your browser the date-time will reflect the data that Andy just downloaded.  There is only one copy of the data and so any changes will be reflected to all users.

If you are happy with the changes please close.

**Comment by Huh** [comment]
A quick note on updates.  If you are connected to the site and updates are pushed you need to disconnect from the server to see the updates.  This sounds simple, but sometimes it is harder than you might think.

A quick test of the functionality now is to take note of the date-time, click on the download button to get a fresh copy of data from the API, then when the download and processing is finished the date and time should be updated.  Open a new tab in your browser and the file modification information will be read from the file you just created and so should reflect the new date and time.

**Comment by nort0160** [comment]
Thanks Josh. I did a quick check and it seems to be updating the most recent download. The previous behavior was odd in that I would download data and then it may update appropriately when I opened a new tab in my browser, but then opening another tab and doing the exact same thing resulted in a last download date a day or two earlier. Either way, I will close issue.
