### ISSUE TITLE
Herd Composition Code - DAU and annual effects

### ISSUE THREAD

**Issue by nort0160** [Huh/PopR_SDGFP#228]
Hopefully a simple request, but could we get the code specifying the herd composition models with DAU and annual effects? Thanks!

**Comment by Huh** [comment]
I think what you want is in the code section of this repository

https://github.com/Huh/PopR_SDGFP/tree/master/Models/comp

Is that what you are asking for?

**Comment by nort0160** [comment]
Perfect, thanks for updating!
