### ISSUE TITLE
Survival Model AM WT Multistate returns "Survival Modeling Error"

### ISSUE THREAD

**Issue by nort0160** [Huh/PopR_SDGFP#233]
I tried running survival model using data from the subset of adult male white-tailed deer from 2016-2018 from all DAUs. The model did not run and returned the message "Survival Modeling Error."

The model structure was: Multi-state, no covariates (although WSI seems to always be included regardless of this option), no censor, single sex, monthly varying time, space by DAU. I ran for thin=2, burn-in=15k, and 25k MCMC iterations.

Thanks,

Andrew

**Comment by Huh** [comment]
Fixed with most recent update
