### ISSUE TITLE
Survival Data Status Updating???

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#236]
If I download the latest data from the servers in Pierre the last time an animal was monitored is in November or so of 2018.  Is this real?  Has weather, capture or something prevented monitoring in the last few months?

I think the large number of missing values is making survival estimates for 2018 very low.

**Comment by nort0160** [comment]
There was some turnover with IT staff, and we have not been able to push our updates to the server you are reading. The IT staff are currently re-creating the query that was used to process our raw data for the server you read.

In the meantime, the data you read are only updated through the 2018 bio-year (end of Oct 2018 I believe). We intended on running survival models for BioYears 2016, 2017, and 2018, and using those 3 years to update the IPM, therefore we shouldn't need any data past October of 2018. Am I interpreting this correctly?

Once our IT staff have completed their query, they will automatically push updates (daily I believe).

**Comment by Huh** [comment]
Sounds good.  It will not cause problems if animals were observed at some point near the end of the year.

**Comment by 12382** [comment]
I believe this has been fixed now.  January data is coming in now.  I will continue to monitor the sample sizes and data entry for any issues.  I will close this issue.
