### ISSUE TITLE
MS survival error on new 

### ISSUE THREAD

**Issue by lindbloom** [Huh/PopR_SDGFP#237]
Just testing out the new website and get errors when I tried the first 2 models:
1.  mule deer, all dau, all sex, adults, 2007-18; multistate, wsi, sexes different, time monthly, space dau
2. whitetails, same as above

the error message reads "a problem was encountered while fitting the model".  

I went back into model structure and changed to known fate, and then the models ran successfully.

**Comment by Huh** [comment]
That was my fault.  I fixed the model and updated the website.  Thanks for pointing this out.
