### ISSUE TITLE
IPM questions/issues

### ISSUE THREAD

**Issue by lindbloom** [Huh/PopR_SDGFP#246]
Couple quick comments/questions:
1.  every time I try to run an IPM for a single DAU, I get the ouch message.  Seems to still run the IPM, not sure if there's a problem.
2.  harvest slider bar gives an error if you just select 2018, which is what we need the most currently
3.  I'm noticing that several license types are not showing up in some DAUs, even though we had those historically (2007-present).   For example, DAU 1 has no options for type 03 and 08 licenses.

**Comment by Huh** [comment]
The updates have not been pushed as I am fighting a bug in the UI right now.  I will reply to your email shortly with more detail.

**Comment by Huh** [comment]
Please take a look at the SD_DEV site.  I will be updating it further tomorrow morning, but it should give you an idea of the how things are going to function going forward.  I would like to close this issue for the time being and move to the new site.  Feel free to re-open if you like
