### ISSUE TITLE
2015321006 has one line of data

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#25]
Can you check on this animal's encounter history please.  It only has one row of data.

**Comment by gfrc11752** [comment]
Please delete this ID number from the dataset. It was never deployed.

**Comment by gfrc11752** [comment]
How is everything else looking?

**Comment by Huh** [comment]
Really good.  I am just running some different combinations of years, ages, sex, etc. and nothing is failing.  There are a few places where I want to walk through my code step by step and verify its behavior, but so far things look great. Josh Nowak 


     On Tuesday, August 11, 2015 2:32 PM, gfrc11752 <notifications@github.com> wrote:
   

 How is everything else looking?

**Comment by gfrc11752** [comment]
Ok, great! If you have data summaries like total number of unique id’s, adults vs. yoy, sex etc… I could do some more cross referencing on my end as well.
