### ISSUE TITLE
Y Survival Modeling Error

### ISSUE THREAD

**Issue by nort0160** [Huh/PopR_SDGFP#253]
I am trying to run some survival models and getting error for Y. Yesterday I got a couple errors for older age classes, but re-ran the models today and they seemed to work.

Spp=MD, DAU=All, Sex=All, Age=Y, Year=2017, Mod=KF, Cov=None, Cens=None, Sex=Same, Time=Constant, Space=DAU, Automate Convergence.

The same "Survival modeling error" occurred when I tried to run for WTD.

Thanks

**Comment by Huh** [comment]
I found one bug and fixed it.  The change is now live and I just ran a model with the settings you recorded above.

As for the older age classes, I will try a few models, but if you could give me some hints about the settings that would be great.

Thanks,

Josh

**Comment by Huh** [comment]
The bug when running the YOY models was in the post processing steps, was it the same for the adults?

**Comment by nort0160** [comment]
Great thanks. The juveniles and adults are regularly running now, so I am not sure what was going on yesterday. I didn't change anything with the adults when I came into the office this morning, just clicked run again and they worked? Structure for juveniles was the same as for Y, adults the same but, I ran separate for each sex.

A slightly related topic with the server disconnect issues we had discussed in the past. Today while running models, our server disconnected due to a thunderstorm and this resulted in all the PopR windows crashing. Even if the model runs were finished, all the data and results were lost. The workaround was to reopen the window and run the models again.

I know this server disconnect is an issue with Shiny whenever there is an error in the script or server disconnect. Is there anyway to avoid the issues of Shiny when the server disconnects? Even if the data and results tables could be temporarily saved somewhere as soon as the models are finished? This way, if we run a bunch of models overnight, we are not at the mercy of our finicky server which seems to intermittently disconnect, aborting everything in PopR.

**Comment by Huh** [comment]
I can save the state of the site now, so maybe I can come up with a way to save the state each time a model is running. That won't fix the mid model run type issue, but I will think about it.

I started a new issue to track/discuss this idea #254

I am going to close this for now, but if you want it reopened have at it.
