### ISSUE TITLE
Data Summaries - Survival

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#26]
**Rows in the original data v Unique rows**
```R
> nrow(survd)
[1] 30646
> nrow(step1)
[1] 29481
```
*I asked for distinct rows in the data while creating object step1 and the result was the removal of 1,165 rows.*

**Unique Animals**
```R
> length(unique(survd$Id1))
[1] 1549
```

**The following Animals have multiple unit entries - _should probably fix this_**
```R
> uni_id[which(lapply(ff, length) > 1)]
[1] 2015713038 2015713040 2015713041 2015713042 2015713043 2015713044 2015713045 2015713046
```
**A peek at the data summary table**
```R
> sp
Source: local data frame [1,549 x 10]

         ID           Species Unit Ageclass    Sex CaptureDate   FateDate      Fate  Dead Censored
1  20090701 White-tailed Deer  12A    Adult Female  2009-02-17 2009-11-01 Harvested  TRUE    FALSE
2  20090702 White-tailed Deer  12A    Adult Female  2009-02-17 2012-05-01     Alive FALSE     TRUE
3  20090703 White-tailed Deer  12A    Adult Female  2009-02-17 2012-05-01     Alive FALSE     TRUE
4  20090704 White-tailed Deer  12A    Adult Female  2009-02-17 2009-10-01 Harvested  TRUE    FALSE
5  20090705 White-tailed Deer  12A    Adult Female  2009-02-17 2009-06-01     Other  TRUE    FALSE
6  20090706 White-tailed Deer  12A    Adult Female  2009-02-17 2012-05-01     Alive FALSE     TRUE
7  20090707 White-tailed Deer  12A    Adult Female  2009-02-17 2009-07-01     Other  TRUE    FALSE
8  20090708 White-tailed Deer  12A    Adult Female  2009-02-17 2009-04-01     Other  TRUE    FALSE
9  20090709 White-tailed Deer  12A    Adult Female  2009-02-17 2009-11-01     Other  TRUE    FALSE
10 20090710 White-tailed Deer  12A    Adult Female  2009-02-17 2010-09-01     Other  TRUE    FALSE
..      ...               ...  ...      ...    ...         ...        ...       ...   ...      ...
```

**Several metrics of fates, ages, and sex**
```R
> table(sp$Dead)

FALSE  TRUE 
 1030   519 
> table(sp$Censored)

FALSE  TRUE 
  519  1030 

> table(sp$Fate)

    Alive Harvested     Other 
     1024        66       459 
> table(sp$Fate, sp$Species)
           
            Mule Deer White-tailed Deer
  Alive           371               653
  Harvested        24                42
  Other           200               259
> table(sp$Sex, sp$Species)
        
         Mule Deer White-tailed Deer
  Female       408               605
  Male         185               340
> table(sp$Ageclass, sp$Species)
       
        Mule Deer White-tailed Deer
  Adult       274               439
  Fawn        321               515
```

**The number of animals caught in each unit of each sex and ageclass**

```R
> table(sp$Unit, sp$Ageclass, sp$Sex)
, ,  = Female

       
        Adult Fawn
  01A       5   11
  02A       0    1
  02C      16   15
  03A      54   31
  05A       0    0
  12A      44    0
  18A      93   48
  21A      34    7
  41A       0   12
  43A      47   20
  44A       0   16
  45A       0    1
  45D      58   55
  46A       3   13
  49B      67   34
  51A       0    3
  53C      49   25
  54A       4    0
  58A,D     0   17
  59A      46   19
  61A       0    3
  BH      113   49

, ,  = Male

       
        Adult Fawn
  01A       0   16
  02A       0    2
  02C       0   12
  03A      50   26
  05A       0    1
  12A       0    0
  18A       0   53
  21A       0   15
  41A       0   15
  43A       0   29
  44A       0    8
  45A       0    2
  45D       0   58
  46A       0   11
  49B       9   40
  51A       0    2
  53C       0   43
  54A       0    0
  58A,D     0   22
  59A       0   28
  61A       0    9
  BH       21   53

```

**Comment by Huh** [comment]
Nothing to do here, just communication, but it may bring up an issue.

**Comment by gfrc11752** [comment]
Awesome, this is starting to come together!! I will get the multiple unit entries cleaned up and also figure out what the repeated row data was all about. Could you send me a subset of the 1,165 repeated row entries in a csv? Thanks!

I am a little leery about the harvested number. Could you subset number harvested by unit by species?

**Comment by Huh** [comment]
Sure,  I have a question for you though.  One combination of entires I tried was white-tailed deer in 2012, region 3 and many of the animals ended their encounter histories in May of the year.
An example ID is 20090702
This type of cohort issue is not a problem, but it does make survival low because everyone is censored part way through the year. Josh Nowak 


     On Tuesday, August 11, 2015 4:35 PM, gfrc11752 <notifications@github.com> wrote:
   

 Awesome, this is starting to come together!! I will get the multiple unit entries cleaned up and also figure out what the repeated row data was all about. Could you send me a subset of the 1,165 repeated row entries in a csv? Thanks!

I am a little leery about the harvested number. Could you subset number harvested by unit by species?

**Comment by Huh** [comment]
I left all the fates in there, but here you go.

```R
> table(tst$Fate, tst$Unit, tst$Species)
, ,  = Mule Deer

                    
                     01A 02A 02C 03A 05A 12A 18A 21A 41A 43A 44A 45A 45D 46A 49B 51A 53C 54A 58A,D 59A 61A  BH
  Alive                0   2  36   0   0   0   0  44  10   0   0   1  47   0  75   0   0   4     4  78   0  65
  Capture Myopathy     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0     0   0   0   2
  Collar Fell Off      0   0   1   0   0   0   0   2   0   0   0   0   0   0   0   0   0   0     0   0   0   2
  Collar Tore Off      0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0     0   0   0   0
  Hunter Harvest       0   0   0   0   0   0   0   0   0   0   0   0  12   0  12   0   0   0     0   0   0   0
  Natural Death        0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0     0   0   0   4
  Other                0   1   0   0   0   0   0   0  10   0   0   1  59   0  63   0   0   0     9   0   0   0
  Probable Predation   0   0   6   0   0   0   0   6   0   0   0   0   0   0   0   0   0   0     1   6   0  12
  Unknown Death        0   0   1   0   0   0   0   3   0   0   0   0   0   0   0   0   0   0     0   9   0   5
  Vehicle Collision    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0     0   0   0   0

, ,  = White-tailed Deer

                    
                     01A 02A 02C 03A 05A 12A 18A 21A 41A 43A 44A 45A 45D 46A 49B 51A 53C 54A 58A,D 59A 61A  BH
  Alive               25   0   0 130   1  17  96   0   5  66   8   1  31  20   0   2 101   0     5   0   8 118
  Capture Myopathy     0   0   0   8   0   0   0   0   0   0   0   0   0   0   0   0   0   0     0   0   0   1
  Collar Fell Off      0   0   0   4   0   0   0   0   0   2   0   0   4   0   0   0   0   0     1   0   0   4
  Collar Tore Off      0   0   0   1   0   0   1   0   0   0   0   0   0   0   0   0   0   0     1   0   0   2
  Hunter Harvest       0   0   0   0   0  10  24   0   0   5   1   0   0   0   0   0   1   0     1   0   0   0
  Natural Death        2   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0     1   0   0   0
  Other                3   0   0   0   0  17  73   0   2  19  15   0  10   7   0   3  16   0    11   0   4   0
  Probable Predation   2   0   0  10   0   0   0   0   0   3   0   0   4   0   0   0   0   0     5   0   0  16
  Unknown Death        0   0   0   7   0   0   0   0   0   1   0   0   3   0   0   0   0   0     1   0   0   5
  Vehicle Collision    0   0   0   0   0   0   0   0   0   1   0   0   1   0   0   0   0   0     0   0   0   1


```

**Comment by gfrc11752** [comment]
Yeah, that is because I used June 1 – May 31 as the deer calendar year and ceased monitoring after May 31 for that group of animals because sample size was not sufficient for analysis. We could project survival using monthly survival rates to adjust for the lower survival rate.

**Comment by gfrc11752** [comment]
How are you dealing with the animals that were assigned a mortality record as censored from the r_merge script but are still being monitored and have an encounter history as alive after the mortality record?? Just curious.

**Comment by gfrc11752** [comment]
This summary states 1024 are alive but I don’t agree because when the animal was censored it says it was censored alive, but we  do have occasions were we censor dead animals. I would like to see a summary table of “currently alive”, “censored”, “harvest” and “other” for peace of mind sake. Just a bit nervous about how the model is treating the censored animals.

Thanks!

**Comment by Huh** [comment]
*How are you dealing with the animals that were assigned a mortality record as censored from the r_merge script but are still being monitored and have an encounter history as alive after the mortality record?? Just curious.*

## For Reporting in the Raw Data Table

```R
			sp <- x %>%
					group_by(ID) %>%
					mutate(Fate = ifelse(grepl("censor", Fate, ignore.case = T),
								"Alive", Fate),
							Fate = ifelse(grepl("natural", Fate, ignore.case = T),
								"Natural Death", Fate),							
							Fate = ifelse(grepl("unknow", Fate, ignore.case = T),
								"Unknown Death", Fate),
							Fate = gsub("other", "Other", Fate),
							Fate = gsub("alive", "Alive", Fate)) %>%
					summarise(Species = find_uni(Species),
								Unit = find_uni(Unit)[1],
								Ageclass = find_uni(Ageclass, age = T),
								Sex = find_uni(Sex),
								CaptureDate = min(Date, na.rm = T),
								FateDate = max(Date, na.rm = T),
								Fate = find_uni(Fate, fate = T),
								Dead = find_uni(Dead, dead = T)) %>%
					mutate(Dead = as.logical(Dead),
							Censored = !Dead)			
```

So, first we group the data by animal ID and then we replace any censored like fate entries with alive, shorten the natural death entry, standardize unknown deaths, standardize other and standardize alive....this is for appearance largely.  Then we find a single value for each animal for species, unit ageclass, sex, capture date, fate date, fate and dead.  The value of capture date is the minimum entry in the data.  The value of fate date is the largest date recorded in the data.  The fate is a little different, we find the unique values in fate and then we go looking for all values that are not alive and if any values are not equal to alive then we take the first entry as the animal's fate.  This is necessary because some have multiple calls, the code looks like this...

```R
				if(fate){
					index <- grepl("alive", out, ignore.case = T)
					if(any(!index)){
						out <- out[!index][1]
					}else{
						out <- "Alive"
					}
				}
```

For the dead value we simply look for any entry that suggests the animal is dead and report dead if any value suggests the animal died, even if it was said to be alive earlier.

When you use the website to do this the answer changes by analysis.  So, say some animal collared in 2010 died in 2012 and you want to do an analysis on 2011.  In this case the animal will be captured on October 1, 2010 and be censored as alive on Sept 30, 2011.  The animal is not seen as dead by this analysis, but it will be dead when you move to 2012.

##  For the actual analysis
- Subset data to time and place of  interest
- Find the first occasion in this new dataset when the animal was observed, but if first is equal to the last occasion in the analysis remove the animal because it never experienced a transition during the time period specified, this is different for adults/juveniles and fawns because fawn analyses only cover 4 months and the others are 12
- Find the last occasion on which the animal was observed, but if the first equals the last then add one to last
- To determine the animal's fate during the analysis simply take the maximum Status value entered (e.g. 1, 2, 3)

Then we can build the encounter histories as follows, assuming known fate:
```R
				eh <- matrix(NA, nrow = nrow(indref), ncol = 
								switch(input$surv_age, "Fawn" = 4, 12))
				for(i in 1:nrow(eh)){
					eh[i, indref$first[i]:(indref$last[i] - 1)] <- 1
					eh[i, indref$last[i]] <- indref$fate[i]
				}

			       if(!ms){
				        #  If not a multi-state model make all deaths = 0
				        eh[eh > 1] <- 0
			      }
```


So, for any given analysis the only thing that matters is the value of first, last and status.  Note: the value of indref$fate[i] is the maximum value of status for that animal.  The fate column is for subsetting (e.g. excluding capture myopathy) and presentation.

**Comment by Huh** [comment]
*I would like to see a summary table of “currently alive”, “censored”, “harvest” and “other” for peace of mind sake.*

"Alive" in the sense that I used it above simply means that they do not contribute a death to the analysis.  Alive can be seen as the sum of still alive, censored, collar tore off, collar fell off and anything else that was not recorded as death (i.e. Status = 2|3).  

The max value of status for all animals in the data are summarize here, this gets rid of the words censored and alive:
```R
> tst <- survd %>%
+ group_by(Id1) %>%
+ summarise(stat = max(Status, na.rm = T))
> table(tst$stat)

   1    2    3 
1023   66  459 

```

Def:  survd is the raw data without any manipulation.  FWIW, the code above groups the animals by their Id1 and then summarise by taking the maximum value of Status observed for each animal, such that the data now has nrow equal to the number of individuals and there is one max value of status for each animal.  These values are then presented by counting how many of each of them there are using table.

So, 1023 animals never had an entry of 2 or 3 and so were never recorded as having been observed dead.  66 animals died by harvest and 459 died by some other cause.

**Comment by gfrc11752** [comment]
Sounds good, I appreciate the explanation.

**Comment by gfrc11752** [comment]
Got it, thanks.

**Comment by Huh** [comment]
Sure, but I trust your experience and your gut, so if something doesn't seem right please let me know.  You know this data better than anyone and that experience is priceless.

**Comment by gfrc11752** [comment]
I appreciate that, once I start running survival estimates on the web site I am assuming more questions may arise. As for now, I think it is starting to come together nicely!
