### ISSUE TITLE
Missing information about sex of ID's

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#27]
```R
> unique(subset(out, is.na(Sex))$ID)
2015111010 
2015221027 
2015311028 
2015311089 
2015311090 
2015311091 
2015311100 
2015321006 
2015511027 
2015511028 
2015711002
```

The above animals are missing sex assignment

**Comment by gfrc11752** [comment]
2015711002 - Never sexed at capture
2015511027 - Never sexed at capture
2015511028 - No, capture record - added into master -male
2015311028 - Never sexed at capture
2015221027 - Never sexed at capture
2015111010 - Never sexed at capture
2015311089 - Does not exist, should be 2015311038
2015311090 - Does not exist, should be 2015311039
2015311091 - Does not exist, should be 2015311040
2015311100 - Does not exist, should be 2015311049
2015321006 - Does not exist - delete

**Comment by Huh** [comment]
Thank you so much Josh Nowak 


     On Tuesday, August 18, 2015 10:26 AM, gfrc11752 <notifications@github.com> wrote:
   

 2015711002 - Never sexed at capture
2015511027 - Never sexed at capture
2015511028 - No, capture record - added into master -male
2015311028 - Never sexed at capture
2015221027 - Never sexed at capture
2015111010 - Never sexed at capture
2015311089 - Does not exist, should be 2015311038
2015311090 - Does not exist, should be 2015311039
2015311091 - Does not exist, should be 2015311040
2015311100 - Does not exist, should be 2015311049
2015321006 - Does not exist - delete—

**Comment by Huh** [comment]
I am trying to setup the IPM, but am now getting a bunch of animals without sex information, did something change?

Animal ID's without sex are shown below:

```R
> rawd %>% filter(is.na(Sex)) %>% select(ID) %>% distinct() %>% as.data.frame()
           ID
1  2015111010
2  2015221027
3  2015221060
4  2015221065
5  2015221082
6  2015221098
7  2015221099
8  2015221100
9  2015221101
10 2015221102
11 2015311028
12 2015311056
13 2015311059
14 2015311063
15 2015311067
16 2015311071
17 2015311074
18 2015311077
19 2015311079
20 2015311083
21 2015311084
22 2015311085
23 2015311086
24 2015311089
25 2015311090
26 2015311091
27 2015311100
28 2015321090
29 2015321091
30 2015321092
31 2015321096
32 2015321098
33 2015321099
34 2015321100
35 2015511027
36 2015611057
37 2015611059
38 2015611060
39 2015611062
40 2015611063
41 2015611066
42 2015611070
43 2015611075
44 2015611077
45 2015611078
46 2015611079
47 2015611082
48 2015611083
49 2015611084
50 2015611087
51 2015611088
52 2015611096
53 2015611098
54 2015611100
55 2015611101
56 2015611102
57 2015611103
58 2015611104
59 2015611106
60 2015611108
61 2015711002
62 2015711060
63 2015711061
64 2015711063
65 2015711064
66 2015711067
67 2015711069
68 2015711084
69 2015711105
70 2015711110
71 2015711111
72 2015711112
```

**Comment by HeatherMcW** [comment]
Kristin check all of the backups from data pulled out of CyberTracker and nothing has changed on our end.

**Comment by HeatherMcW** [comment]
Josh, where are you getting these ID #'s from? We do not have any records for the majority of the IDs you listed.

**Comment by gfrc11752** [comment]
Yes, Heather is correct. Most of the ID's referenced above do not exist....

**Comment by Huh** [comment]
API download

**Comment by Huh** [comment]
Hmmm, let me dig a little more
