### ISSUE TITLE
Pregnancy Data in DB

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#28]
When downloading using the webservice the pregnancy data is a bit messy, for example:

```R
> unique(xx$Unit)
[1] "North ER " "South ER " "BH1"      
> unique(xx$Ageclass)
[1] "Adult"    "Fawn"     "Yearling" "yearling" "adult"    "yoy"      "juv" 
```

Just an FYI for later.  I can fix these things on my end, but I would prefer to have the db squeaky clean.

**Comment by gfrc11752** [comment]
Heather, can you clean up the pregnancy table in the database, all yearlings and fawns should be “juv” and all adults should be “adult”.

Josh, how are handling the unit assignments (North ER and South ER)?

**Comment by Huh** [comment]
I wrote the code to use north.east and the like, but will have to change it for North ER.  This data seems different to me now, but I will have to verify.  Anyway, I let you estimate at the scales in the data for the time being.  The IPM database used statewide estimates where age and year were unique, but no spatial subsetting was taken into account. Josh Nowak 


     On Tuesday, August 18, 2015 3:25 PM, gfrc11752 <notifications@github.com> wrote:
   

 Heather, can you clean up the pregnancy table in the database, all yearlings and fawns should be “juv” and all adults should be “adult”.

Josh, how are handling the unit assignments (North ER and South ER)?

**Comment by Huh** [comment]
This behavior was changed to better align with other data sources.  DAU is now the spatial arrangement that is relied upon for analyses.  For all of the data if unit is present an attempt is made to assign DAU to the observation, when unit is missing DAU is missing.  To use data with missing DAU the user must select DAU == "All"
