### ISSUE TITLE
Survival - Repeat observations?

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#33]
```R
           ID   Species BioYear Month DAU Unit.x Ageclass Sex       Date Status Fate Censored Dead
1  2010123001 Mule Deer    2010     1  NA    49B    adult   f 2010-01-26      1   NA       NA   NA
2  2010123001 Mule Deer    2010     1  NA    49B    adult   f 2010-01-26      1   NA       NA   NA
3  2010123001 Mule Deer    2010     2  NA    49B    adult   f 2010-02-01      1   NA       NA   NA
```

There are many observations like the data above.  Some of the fawns are monitored daily too, is that real?

If you only look at this animal's data you may notice that it has several observations on 07/14/2015.  In addition, Kevin's new data is in the database along with older data sources.

Thoughts?

**Comment by Huh** [comment]
FWIW, all of these animals were captured twice

```R
2013521012 2013521013 2013521014 2013521015 2013521016 2013521017 2013521018 2013521019 2013521020 
         2          2          2          2          2          2          2          2          2 
2013521021 2013521022 2013521023 2013521024 2013521025 2013521026 2013521027 2013521028 2013521029 
         2          2          2          2          2          2          2          2          2 
2013521030 2013521031 2013521032 2013521033 2015321008 
         2          2          2          2          2 

```

**Comment by gfrc11752** [comment]
Yes, some fawns especially in the Black Hills were being monitored daily for the first few weeks of life to determine CSM. 

The issue regarding repeated observations is a result of people entering multiple monitoring events on that day and thinking they changed the dates but the data stored in the ftp site overwrote the modified data thus multiple records occur on the same day. This issue has been fixed on our end in Cybertracker. I thought I had cleaned those up but obviously I missed a few.

**Comment by gfrc11752** [comment]
That is strange, I just went through the file and only 2015321008 has a duplicate capture record…

**Comment by Huh** [comment]
Maybe it is the indexing of the ID from the API, I will check. Josh Nowak 


     On Tuesday, September 1, 2015 12:56 PM, gfrc11752 <notifications@github.com> wrote:
   

 That is strange, I just went through the file and only 2015321008 has a duplicate capture record…

**Comment by gfrc11752** [comment]
ID1 is the one we need.

**Comment by Huh** [comment]
Yes, I used ID sloppily, sorry. Josh Nowak 


     On Tuesday, September 1, 2015 1:22 PM, gfrc11752 <notifications@github.com> wrote:
   

 ID1 is the one we need.

**Comment by Huh** [comment]
To the point about duplicate records, your email indicated that your master copy did not have the duplicates, but I am pulling form the DB directly, so it could be different.

**Comment by gfrc11752** [comment]
I may have not gotten all duplicate records cleaned up, how many duplicate rows are getting?

**Comment by Huh** [comment]
Animal without Sex entries
```R
> unique(subset(surv$data, is.na(Sex))$ID)
 [1] "2015221027" "2015221060" "2015221065" "2015221082" "2015221098" "2015221099" "2015221100" "2015221101"
 [9] "2015221102" "2015321090" "2015321091" "2015321092" "2015321096" "2015321098" "2015321099" "2015321100"
```

To calculate the number of duplicated rows I first subset the data to only include ID1, Date1 and Status.  After doing that I asked R to subset the data by returning only unique rows.  The original data had 35,621 rows and the unique data had 32,042 

```R
> tst <- survd %>% select(ID1, Date1, Status) %>% distinct()
> nrow(tst)
[1] 32042
> nrow(survd)
[1] 35621
```

As a general data comment, we have a lot of "" and " " entries, just blanks and spaces.  While I am catching them on my end this is not the best practice moving forward.  Each cell of the data should have NA or a value.  Just an FYI, I think this has been handled within the data entry tools.

**Comment by Huh** [comment]
If I don't subset the columns and use all of the columns then the raw data still has 35,621 rows, but it now finds 33,620 unique rows.  This implies that there are 2001 duplicates...funny how close that number is to the number of records we can download at once from the API.

**Comment by Huh** [comment]
Ok, I fixed the duplicates in terms of the API download and so now if I do no subsetting of columns then I get 33,620 from the raw data and there are that many unique rows.  However, if I subset the columns to ID1, Date1 and Status I still have 1,578 duplicated rows.

**Comment by gfrc11752** [comment]
Something is not working properly, I have 30,180 rows in the latest csv file I sent you.

**Comment by Huh** [comment]
How was the data in the database created?  How many rows are in the database?  Could someone connect directly and see how many entries there are?

**Comment by gfrc11752** [comment]
33,619 rows are in the database as of right now

**Comment by gfrc11752** [comment]
I have figured out the problem and it will be getting resolved tomorrow.

**Comment by Huh** [comment]
You were talking about 2009 data today.  My dates go from 2010-01-26 to 2015-08-21.

I tabled the number of observations in each year for fun...
```R
> table(tmp$BioYear, tmp$Sex)
      
       Female Male
  2010    740   69
  2011    938   64
  2012    953   38
  2013   1451  579
  2014   2129 1361
  2015   4306 1991
```

So if you had 9 males observed for 12 months you would have 108 observations, so the above seems reasonable.

**Comment by gfrc11752** [comment]
That is another serious problem…My dates go from 2/17/2009 – 8-21-2015..
