### ISSUE TITLE
Harvest

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#34]
We previously discussed Unit 09A.  The decision made was to put 80% of 09A harvest into BD1 and 20% into 15B.  I would like for this change to occur in the database.  Is this a possibility?

**Comment by HeatherMcW** [comment]
Do you want a systematic approach or just change the unit for the first 80% of records listed each year?

**Comment by Huh** [comment]
My goal is to get one entry per Unit, Year, UserGroup, TagType...

What would a systematic approach be on your end?  The unit does not exist, but has harvest for just a handful of years.

**Comment by HeatherMcW** [comment]
Kevin got me straight on this issue. The database has been updated. Let me know if any weird issues popped up from it.

**Comment by Huh** [comment]
If is resolved please close the issue...it makes it look like we are making progress=)

I would do it, but I am not close enough to the fix/fixer.

**Comment by Huh** [comment]
This issue has not been fixed, I am still getting 09A entries from the harvest database table.

**Comment by gfrc11752** [comment]
Talking to Heather now......

**Comment by HeatherMcW** [comment]
This is fixed, my mistake.

**Comment by Huh** [comment]
Thank you Heather. Josh Nowak 


     On Friday, October 16, 2015 8:24 AM, HeatherMcW <notifications@github.com> wrote:
   

 Closed #34.—
