### ISSUE TITLE
Harvest DB

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#35]
I found a TagType 41 on line 503 of the harvest database.  If this tagtype never existed please correct.

**Comment by gfrc11752** [comment]
Heather can you please delete any 41 tag types in the database?

**Comment by HeatherMcW** [comment]
This record has been deleted.

**Comment by Huh** [comment]
Thank you....closing
 Josh Nowak 


     On Wednesday, September 2, 2015 1:03 PM, HeatherMcW <notifications@github.com> wrote:
   

 This record has been deleted.—
