### ISSUE TITLE
Region 2: 2015 WTD fawns

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#39]
Should have 48 records/entries not 38...MIssing data!

**Comment by Huh** [comment]
What are all the settings?  This is survival, right?

Year - 2015 
Region - ?
Unit - ?
Sex - ?
Fawn - ?

Any exclusions of censor or mort types?

**Comment by gfrc11752** [comment]
No exclusions, yes those would be right.

**Comment by Huh** [comment]
I don't understand.

I downloaded data from the API 
Year - 2015 
Region - All
Unit - All
Sex - All
Age - yoy
Species - White-tailed Deer

And I have 351 unique individuals.  What did I do wrong?

**Comment by gfrc11752** [comment]
•      2013

–     168 fawns were captured and collared

•       83 Mule Deer

•       85 Whitetails

•      2014

–     271 fawns were captured and collared

•       89 Mule Deer

•       182 Whitetails

•      2015

–     387 fawns were captured and collared

•       148 Mule Deer

•       241 Whitetails

•      Total 828 (320 MD and 508 WTD)

Here are the totals by year we should have…Not sure what the heck is going on!

**Comment by Huh** [comment]
Without doing anything to the data the sample sizes look like:

```R
> tst <- survd %>%
+ mutate(Date = as.Date(Date1, "%m/%d/%Y"),
+ Year = as.numeric(format(Date, "%Y"))) %>%
+ group_by(Year, AgeClass, Species) %>%
+ summarise(ID = length(unique(ID1)))
> tst
Source: local data frame [20 x 4]
Groups: Year, AgeClass

   Year AgeClass           Species  ID
1  2009    adult White-tailed Deer  51
2  2010    adult         Mule Deer  96
3  2010    adult White-tailed Deer  76
4  2011    adult         Mule Deer  96
5  2011    adult White-tailed Deer  55
6  2012    adult         Mule Deer  90
7  2012    adult White-tailed Deer  62
8  2013    adult         Mule Deer  74
9  2013    adult White-tailed Deer  64
10 2013      yoy         Mule Deer  83
11 2013      yoy White-tailed Deer  85
12 2014    adult         Mule Deer  57
13 2014    adult White-tailed Deer 139
14 2014      yoy         Mule Deer 129
15 2014      yoy White-tailed Deer 211
16 2015    adult         Mule Deer 195
17 2015    adult White-tailed Deer 325
18 2015      yoy         Mule Deer 207
19 2015      yoy White-tailed Deer 351
20   NA                              1
```

The adult ageclass won't be the number captured in a given year necessarily.  The yoy might be high too if data entry techniques fill in yoy for all entires of a given individual.  I tried to get the number of captures each year using:
```R
> survd %>%
+ mutate(Date = as.Date(Date1, "%m/%d/%Y")) %>%
+ group_by(ID1) %>%
+ summarise(Capture = min(Date, na.rm = T),
+ AgeClass = AgeClass[1],
+ Species = unique(Species)) %>%
+ mutate(Year = as.numeric(format(Capture, "%Y"))) %>%
+ group_by(Year, AgeClass, Species) %>%
+ summarise(Caps = n())
Source: local data frame [17 x 4]
Groups: Year, AgeClass

   Year AgeClass           Species Caps
1  2009    adult White-tailed Deer   51
2  2010    adult         Mule Deer   96
3  2010    adult White-tailed Deer   37
4  2011    adult         Mule Deer   18
5  2012    adult         Mule Deer   20
6  2012    adult White-tailed Deer   20
7  2013    adult White-tailed Deer   29
8  2013      yoy         Mule Deer   83
9  2013      yoy White-tailed Deer   85
10 2014    adult White-tailed Deer   95
11 2014      yoy         Mule Deer   89
12 2014      yoy White-tailed Deer  182
13 2015    adult         Mule Deer  141
14 2015    adult White-tailed Deer  209
15 2015      yoy         Mule Deer  163
16 2015      yoy White-tailed Deer  296
17   NA                               1
```

Those numbers are closer.  FWIW, the yoy entries bleeding over is not an issue for the software as animals are aged when the data is first read in and the original entries deleted except the first.

So, do you have a list of ID's for each year's capture?  I can tell you who is extra in just a few moments if you do.  I have a meeting for the next hour, be back soon.

**Comment by gfrc11752** [comment]
Couldn’t we generate that list by querying out collection type “capture” by year?

**Comment by Huh** [comment]
It produces about the same result as what I did before filtering out by minimum date, but these data will count individuals without a "Deer Capture" entry.  

```R
> survd %>%
+ mutate(Date = as.Date(Date1, "%m/%d/%Y"),
+ Year = as.numeric(format(Date, "%Y"))) %>%
+ group_by(Year, AgeClass, Species) %>%
+ summarise(Caps = sum(CollectionType == "Deer Capture"))
Source: local data frame [20 x 4]
Groups: Year, AgeClass

   Year AgeClass           Species Caps
1  2009    adult White-tailed Deer   51
2  2010    adult         Mule Deer   96
3  2010    adult White-tailed Deer   37
4  2011    adult         Mule Deer   18
5  2011    adult White-tailed Deer    0
6  2012    adult         Mule Deer   20
7  2012    adult White-tailed Deer   20
8  2013    adult         Mule Deer    0
9  2013    adult White-tailed Deer   29
10 2013      yoy         Mule Deer   83
11 2013      yoy White-tailed Deer   85
12 2014    adult         Mule Deer    0
13 2014    adult White-tailed Deer   95
14 2014      yoy         Mule Deer   89
15 2014      yoy White-tailed Deer  182
16 2015    adult         Mule Deer  141
17 2015    adult White-tailed Deer  210
18 2015      yoy         Mule Deer  149
19 2015      yoy White-tailed Deer  244
20   NA                               0

```

**Comment by gfrc11752** [comment]
All unique ID’s should have a deer capture entry.

**Comment by Huh** [comment]
But I don't think they do because a few of those numbers are different in my two summaries. Josh Nowak 


     On Wednesday, September 2, 2015 3:32 PM, gfrc11752 <notifications@github.com> wrote:
   

 All unique ID’s should have a deer capture entry.

**Comment by gfrc11752** [comment]
This is looking better… I must have 6 yoy (4 wtd, 2 md) in 2015 with no capture record.

**Comment by Huh** [comment]
Yes and also too many ID1 entries for the number of animals.

It is concerning that these two numbers are different:
```R
                                   IDs    Deer Captures
14 2015    adult White-tailed Deer  209 210
15 2015      yoy         Mule Deer  163 149
16 2015      yoy White-tailed Deer  296 244
```

**Comment by gfrc11752** [comment]
Not good, working on a resolution now. Stayed tuned.

**Comment by Huh** [comment]
I assume this was handled, please close if you recall finding a solution.  The data check and the like that we do now should be taking care of reporting these types of errors.
