### ISSUE TITLE
Website crashed

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#41]
The website has ceased working after my request in the composition data tab. all years, region 4.

**Comment by Huh** [comment]
Species? Josh Nowak 


     On Wednesday, September 2, 2015 3:22 PM, gfrc11752 <notifications@github.com> wrote:
   

 The website has ceased working after my request in the composition data tab. all years, region 4.—

**Comment by gfrc11752** [comment]
white-tailed deer

**Comment by Huh** [comment]
I can't seem to reproduce the error.  There is data for that set of inputs.  Is there anything else that you can think of that would help me to reproduce the error? Josh Nowak 


     On Wednesday, September 2, 2015 3:28 PM, Josh Nowak <Joshnwk@yahoo.com> wrote:
   

 Species? Josh Nowak 


     On Wednesday, September 2, 2015 3:22 PM, gfrc11752 <notifications@github.com> wrote:
   

 The website has ceased working after my request in the composition data tab. all years, region 4.—

**Comment by gfrc11752** [comment]
WTD, R4, All Units, All Years, Fit Model – just tried it again. I think it is timing out??

**Comment by Huh** [comment]
Yes, that makes sense.  The data are huge for that set of values and it may take more time than one of the many timeouts involved.  
I will add an email me the results type entry and look at making it faster.  Bummer that it worked for me and not you.  
How long does it take, roughly? Josh Nowak 


     On Wednesday, September 2, 2015 3:49 PM, gfrc11752 <notifications@github.com> wrote:
   

 WTD, R4, All Units, All Years, Fit Model – just tried it again. I think it is timing out??

**Comment by gfrc11752** [comment]
It is still trying to run….5+ minutes

**Comment by Huh** [comment]
Now #73 the option to get email results will be part of every tab
