### ISSUE TITLE
API Tag Potential Data

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#46]
I don't believe the tag potential data is what was intended....see below for output of download from this table.  This is useful too, but I thought the 3 year average of number killed on each tag in each unit would be in there.  Am I just wrong?

```R
   PrimaryID TagType                                        Description PotWBA PotWBF PotWDA PotWDF PotMBA PotMBF PotMDA PotMDF
1          1      01                                           any deer      1      1      1      1      1      1      1      1
2          2      02                                      any buck deer      1      1      0      0      1      1      0      0
3          3      03                                any antlerless deer      0      1      1      1      0      1      1      1
4          4      05                     any buck deer 2 points or more      1      0      0      0      2      0      0      0
5          5      06                 any deer and 2 any antlerless deer      1      3      3      3      1      3      3      3
6          6      07                              3 any antlerless deer      0      3      3      3      0      3      3      3
7          7      08                   any deer and any antlerless deer      1      2      2      2      1      2      2      2
8          8      09        any antlerless deer and any antlerless deer      0      2      2      2      0      2      2      2
9          9      11                                 any whitetail deer      1      1      1      1      0      0      0      0
10        10      13                          antlerless whitetail deer      1      1      1      1      0      0      0      0
11        11      16 any whitetail deer and 2 antlerless whitetail deer      1      3      3      3      0      0      0      0
12        12      17                        3 antlerless whitetail deer      0      3      3      3      0      0      0      0
13        13      18   any whitetail deer and antlerless whitetail deer      1      2      2      2      0      0      0      0
14        14      19                        2 antlerless whitetail deer      0      2      2      2      0      2      2      2
```

**Comment by gfrc11752** [comment]
No, that looks like maximum harvest potential by tag type, sex, age and species. 
We need 3-yr harvest averages by tag-type, species, sex and age. For example, 1 - 01 tag-type in 2A on average harvests 0.21 md bucks, 0.05 md does, 0.28 wtd bucks and 0.09 wtd- add these up to get the 3-yr success rate for that 01-tagtype. 3-yr average 63% tag success.

**Comment by Huh** [comment]
That is the data I was expecting. Josh Nowak 


     On Thursday, September 3, 2015 11:24 AM, gfrc11752 <notifications@github.com> wrote:
   

 No, that looks like maximum harvest potential by tag type, sex, age and species. 
We need 3-yr harvest averages by tag-type, species, sex and age. For example, 1 - 01 tag-type in 2A on average harvests 0.21 md bucks, 0.05 md does, 0.28 wtd bucks and 0.09 wtd- add these up to get the 3-yr success rate for that 01-tagtype. 3-yr average 63% tag success. —

**Comment by gfrc11752** [comment]
Was that a table Heather provided or was that something you derived?

**Comment by Huh** [comment]
I had nothing to do with it.  It was an option in the API is all I know and I was working on calculating expected harvest from tag numbers. Josh Nowak 


     On Thursday, September 3, 2015 11:53 AM, gfrc11752 <notifications@github.com> wrote:
   

 Was that a table Heather provided or was that something you derived?

**Comment by gfrc11752** [comment]
Mayday….

**Comment by Huh** [comment]
Ha Josh Nowak 


     On Thursday, September 3, 2015 12:11 PM, gfrc11752 <notifications@github.com> wrote:
   

 Mayday….

**Comment by HeatherMcW** [comment]
This was something I came up with that I thought might have been useful, but I didnt really have a good plan for it. 

What can I do on my end to make a true tag potential?

**Comment by HeatherMcW** [comment]
I have enter tags available for East River. West River, Black Hills, and Refuges for all years

let me know if you need anything to calculate tag potential
