### ISSUE TITLE
Install abort button while retrieving data

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#47]
Write a line of code that immediately ceases data upload through the API. This will make for a better user experience when selecting large quantities of data and getting timed out. Right now you have to completely close out of the website.

**Comment by Huh** [comment]
I don't understand your comment. Josh Nowak 


     On Thursday, September 3, 2015 11:26 AM, gfrc11752 <notifications@github.com> wrote:
   

 Write a line of code that immediately ceases data upload through the API. This will make for a better user experience when selecting large quantities of data and getting timed out. Right now you have to completely close out of the website. —

**Comment by gfrc11752** [comment]
If a user selects the composition tab and selects all years  - WTD, R1  , the running models icon stays on for 10 minutes and the blue bar doesn't move. The only way to cease the operation is to close out completely. It would be nice to have an "abort data upload" button so if this continues to happen the user can cease the upload and start over - sub-setting at a different level.

**Comment by Huh** [comment]
Thanks for the clarification.  It sounds like this is happening during a model run and not during download. 
Does this happen after hitting the get data button or fit model?
Aborting a model run is not simple and the results of cancelling the operation vary from what you might you expect to crashing R completely.
If this is happening after fit model is pressed, then I think the warning about how long the model may take might be a solution and emailing results would be another or complimentary solution. Josh Nowak 


     On Thursday, September 3, 2015 11:51 AM, gfrc11752 <notifications@github.com> wrote:
   

 If a user selects the composition tab and selects all years - WTD, R1 , the running models icon stays on for 10 minutes and the blue bar doesn't move. The only way to cease the operation is to close out completely. It would be nice to have an "abort data upload" button so if this continues to happen the user can cease the upload and start over - sub-setting at a different level.—

**Comment by gfrc11752** [comment]
Yes, you are correct, my bad. This refers to the “fit model” button. Yes, your suggestion  sounds reasonable.

**Comment by Huh** [comment]
Closing in favor of #73 also related to closed issue #41
