### ISSUE TITLE
Missing pregnancy data

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#48]
When I load the WTD preg data for R3 and R4 I get nothing. Might want to give it a try....

**Comment by Huh** [comment]
Fixed spatial lookup function to be more general.
For your information this was a result of some datasets not having a Region column.
Thanks for catching this, Josh Nowak 


     On Thursday, September 3, 2015 12:05 PM, gfrc11752 <notifications@github.com> wrote:
   

 When I load the WTD preg data for R3 and R4 I get nothing. Might want to give it a try....—

**Comment by gfrc11752** [comment]
Spatial lookup function isn't assigning units to the correct DAU?

**Comment by Huh** [comment]
Wrong DAU or no DAU?  I can't assign a DAU for most of the existing data because there is no unit information.

**Comment by gfrc11752** [comment]
Is the IPM using the lumped data then?

**Comment by Huh** [comment]
Yes, the IPM uses a statewide pregnancy estimate for adults and juveniles.
PregnancyAdults: 0.91 (0.03)Juveniles: 0.53 (0.05)
Fetus CountAdults: 1.78 (0.05)Juvenile: 1.54 (0.07)
All parameters assumed to be Normally distributed.  Pregnancy is truncated between 0 and 1 while Fetus Count is constrained to be larger than 0. Josh Nowak 


    On Thursday, December 3, 2015 1:26 PM, gfrc11752 <notifications@github.com> wrote:
 

 Is the IPM using the lumped data then?—

**Comment by gfrc11752** [comment]
Perfect!

**Comment by gfrc11752** [comment]
Are we using the same data set for both species?

**Comment by Huh** [comment]
Yes.  There isn't any data for Mule Deer, but if you have different numbers you want added I can change that.  I realize that the numbers should not be the same. Josh Nowak 


    On Thursday, December 3, 2015 1:41 PM, gfrc11752 <notifications@github.com> wrote:
 

 Are we using the same data set for both species?—

**Comment by Huh** [comment]
Close?  

I would like to add a new issue to enhance the handling of pregnancy data in the IPM database.  Now that you have added more data I think we can treat it like the other data sources and stop with the single value for pregnancy that I reported above.
