### ISSUE TITLE
Database column fixes

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#49]
Heather,

Could you please change Lat and Long to Latitude and Longitude in the Pregnancy data set

Also, please add column DAU to all data sets.  Survival has this column.  The values can be NULL or blank, we will update later.

Thank you,
Josh

**Comment by HeatherMcW** [comment]
are you confident this is the last change to all of the field headings? Can I add the DAU field as the end column or do the columns need to be in a specific order?

**Comment by Huh** [comment]
Order does not matter with the columns.  I believe we can call this the last change, but I can't be sure.
Thanks, Josh Nowak 


     On Friday, September 4, 2015 7:03 AM, HeatherMcW <notifications@github.com> wrote:
   

 are you confident this is the last change to all of the field headings? Can I add the DAU field as the end column or do the columns need to be in a specific order?—

**Comment by HeatherMcW** [comment]
this should be fixed now

**Comment by Huh** [comment]
Closing because James and Heather told me it is fixed.
