### ISSUE TITLE
Composition data

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#5]
The report, plots and table features are not working in the composition tab. Unit 18A, region 4 was the unit I noticed it on and I didn't check other units.

**Comment by Huh** [comment]
I was not able to reproduce this error.  I was working with white-tailed deer.  I tried using data from just region 4 and when all data were used.  They both functioned as expected for me.  Did you not download the data again after changing something to the left of the download button?

**Comment by gfrc11752** [comment]
Alright, I didn't hit the fit model tab... Change that tab to "Summarize Data". Why is there only 4 entries for 18A, we are definitely missing data for that 2013, 18A summary.
