### ISSUE TITLE
Pregnancy Table

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#51]
Within the pregnancy table: 2015: Black Hills: 6 individuals defined as "juv" need to be changed to "adult".

**Comment by Huh** [comment]
Kevin,
Could you please assign the task to someone.  
Thank you, Josh Nowak 


     On Tuesday, September 8, 2015 3:20 PM, gfrc11752 <notifications@github.com> wrote:
   

 Within the pregnancy table: 2015: Black Hills: 6 individuals defined as "juv" need to be changed to "adult". —

**Comment by gfrc11752** [comment]
I had assigned it to Heather…

**Comment by Huh** [comment]
Sorry, I only looked at the email verison. Josh Nowak 


     On Tuesday, September 8, 2015 3:36 PM, gfrc11752 <notifications@github.com> wrote:
   

 I had assigned it to Heather…

**Comment by gfrc11752** [comment]
Roger that, no problem!

**Comment by HeatherMcW** [comment]
i updated 7 deer classified as "juv" age 2 to adult

**Comment by Huh** [comment]
Close???
