### ISSUE TITLE
Archery Deer Harvest Data

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#55]
Currently, we cannot subset archery harvest by season or user group. Please add to the drop down menus.

**Comment by Huh** [comment]
I don't understand the comment.  I assume we are talking about the harvest tab, but are you saying that archery is not an option in season and user group?

**Comment by gfrc11752** [comment]
Yep, you fixed this already.

**Comment by Huh** [comment]
My favorite reply
