### ISSUE TITLE
Survival Data

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#56]
I found a strange error in the data.  Can someone take a look at Animal 2010123017 and give me a hypothesis or two on what happened, why there is a July 14, 2015 data entry after the mortality event was entered on September of the previous year.

**Comment by gfrc11752** [comment]
2010123017	2010123017	09/01/2014	Mule Deer	2010123017	150.51	1	Alive	NA	49B	NA	adult	f	NA	TRUE	FALSE	NA	NA	NA	NA	NA	NA	NA	NA	NA	Deer Mortality	NA
We censored 2010123017 on 09/01/2014. The API must have created a new entry on 7-14-15. The clean survival encounter version I sent you yesterday does not have an entry for 2010123017 on 7-14-15.

**Comment by Huh** [comment]
Can the API create entries?  Seriously asking, I would think that a very poor design if so... Josh Nowak 


     On Wednesday, September 30, 2015 12:44 PM, gfrc11752 <notifications@github.com> wrote:
   

 2010123017 2010123017 09/01/2014 Mule Deer 2010123017 150.51 1 Alive NA 49B NA adult f NA TRUE FALSE NA NA NA NA NA NA NA NA NA Deer Mortality NA
We censored 2010123017 on 09/01/2014. The API must have created a new entry on 7-14-15. The clean survival encounter version I sent you yesterday does not have an entry for 2010123017 on 7-14-15. —

**Comment by gfrc11752** [comment]
That row of data is not in the sequel database so how else does it get created? Mystery, no idea!!

**Comment by Huh** [comment]
That was sort of my question.  At one point we wondered if the old and new data were both put into the SQL database.  My guess is that that issue was never resolved.  It seems like we get old and new data when we pull from the survival database. Josh Nowak 


     On Wednesday, September 30, 2015 1:17 PM, gfrc11752 <notifications@github.com> wrote:
   

 That row of data is not in the sequel database so how else does it get created? Mystery, no idea!!

**Comment by gfrc11752** [comment]
That was my initial thought as well. I had them wipe the sequel database clean yesterday and insert only the clean data.

**Comment by Huh** [comment]
Whoa....how the.....huh Josh Nowak 


     On Wednesday, September 30, 2015 3:19 PM, gfrc11752 <notifications@github.com> wrote:
   

 That was my initial thought as well. I had them wipe the sequel database clean yesterday and insert only the clean data.

**Comment by gfrc11752** [comment]
My thoughts exactly…I am running out of ideas!

**Comment by HeatherMcW** [comment]
The SQL database has not been cleared yet. I will let you know when it has.

**Comment by gfrc11752** [comment]
Yes, please do, as I thought this was already accomplished!

**Comment by Huh** [comment]
That makes more sense to me.  I couldn't figure out how all of those errors were being injected by the API or me or anything else.  Thanks for the update Heather. 
 


     On Thursday, October 1, 2015 8:24 AM, gfrc11752 <notifications@github.com> wrote:
   

 Yes, please do, as I thought this was already accomplished!—

**Comment by HeatherMcW** [comment]
Josh - I wiped out everything in the Survival Encounter table. Please let me know if this is reflected on your end.

**Comment by Huh** [comment]
Yes, there is nothing in the database now.  I get only the column names and no entries for any fields. Josh Nowak 


     On Thursday, October 1, 2015 12:16 PM, HeatherMcW <notifications@github.com> wrote:
   

 Josh - I wiped out everything in the Survival Encounter table. Please let me know if this is reflected on your end.—

**Comment by HeatherMcW** [comment]
now do you see 32,684 records?

**Comment by Huh** [comment]
32,685
The problem seems to be in row 30,579.  The Source information for this column gets pushed into the PrimaryID of row 30,580, which makes it look like a new record.  This happen because the comments on row 30,579 contain some special character, probably a vertical bar (i.e. | ).
Two thoughts,1.  James/Tyler should escape the table, if possible, before sending the data so that nothing in the table is evaluated.  I don't know exactly what they are doing on their end, so this is a guess and may be a naive suggestion.
2.  Go fix the one funky comment and it will fix the problem
Thank you for this, Josh Nowak 


     On Thursday, October 1, 2015 12:26 PM, HeatherMcW <notifications@github.com> wrote:
   

 now do you see 32,684 records?—

**Comment by HeatherMcW** [comment]
I went with Option #2. Next time we can get BIT over here, I will have them look at escaping the last row. I thought it had already been done...but apparently not.

**Comment by Huh** [comment]
It is not the last row though, it is in the middle of a chunk.  The text that comes to me include lots of ?? a? b/a??? looking stuff.

 Josh Nowak 


     On Thursday, October 1, 2015 1:10 PM, HeatherMcW <notifications@github.com> wrote:
   

 I went with Option #2. Next time we can get BIT over here, I will have them look at escaping the last row. I thought it had already been done...but apparently not.—

**Comment by HeatherMcW** [comment]
Better?

**Comment by Huh** [comment]
I will run the check script and get back to you.  I have been working with the new data since you posted it and everything seems fine so far. Josh Nowak 


     On Thursday, October 1, 2015 1:39 PM, HeatherMcW <notifications@github.com> wrote:
   

 Better?—

**Comment by Huh** [comment]
Ran the script and found a few errors, but it is better than it was.  The survival estimation tab seems quite stable now and I will be updating the website shortly for you to see the problems I found.

**Comment by gfrc11752** [comment]
Thanks for the good news...
