### ISSUE TITLE
Composition Data Count Ranges

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#58]
I ran a series of composition models this afternoon to see if I could get it to fail and noticed an estimate where males were dominating the population.  This was because there was an entry of 569 males counted in that year (PopR settings: Mule Deer, Region 1, 2013, All Units).  So I went back and downloaded the data from the API and found the following summaries of the columns.  It looks like 999 is being used in place of NULL. 

```r
> summary(as.numeric(comp_dat$YOY_Count))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   0.000   1.000   1.342   2.000 200.000    1676 
> summary(as.numeric(comp_dat$Female_Count))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   1.000   1.000   1.551   2.000 999.000     994 
> summary(as.numeric(comp_dat$Male_Count))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   0.000   0.000   0.771   1.000 999.000    3344 
```

**Comment by gfrc11752** [comment]
Heather, can you please do a data search in the herd composition data set for erroneous entries similar to what Josh mentioned. 999's or excessively large entries. Delete the entire entry if you find such examples.

**Comment by HeatherMcW** [comment]
would 14 YOY, 46 Female, 4 Male be an excessively large entry? 08/11/09 with no unit

**Comment by gfrc11752** [comment]
If that is an elk entry no, but a deer entry in august or that large should be deleted. Deer survey dates should be 9-1 thru 10-31.

**Comment by HeatherMcW** [comment]
I deleted all of the records that fell outside of the survey range (9/1 - 10/31) as well as any excessively large numbers. 

FYI the Total Deer column does not always equal YOY + Female + Male. There are a handful of records that include deer of unknown age and sex that only appear in the Total Count Column. (i.e. PrimaryID #48354)

**Comment by Huh** [comment]
The Total not being equal is by design and intended to catch animals not assigned to an age or sex.  The total group size should always be equal to or greater than the sum of the yoy, female and male columns.
Good catch, it takes some vigilance to see things like that. Josh 


     On Tuesday, October 6, 2015 12:36 PM, HeatherMcW <notifications@github.com> wrote:
   

 I deleted all of the records that fell outside of the survey range (9/1 - 10/31) as well as any excessively large numbers. FYI the Total Deer column does not always equal YOY + Female + Male. There are a handful of records that include deer of unknown age and sex that only appear in the Total Count Column. (i.e. PrimaryID #48354)—

**Comment by HeatherMcW** [comment]
closed....?

**Comment by Huh** [comment]
I think so
