### ISSUE TITLE
Here comes the dumb questions......

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#6]
How can you go back and forth between the gitHub  page and the model without having to login again??

**Comment by Huh** [comment]
Open two tabs in your internet browser....one with popr and one with github.  Or, if you have two screens, or want to split your screen, open two instances of interenet explorer/chrome/etc.
 Josh Nowak 


     On Tuesday, July 14, 2015 1:08 PM, gfrc11752 <notifications@github.com> wrote:
   

 How can you go back and forth between the gitHub page and the model without having to login again??—
