### ISSUE TITLE
Survival Broken

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_SDGFP#61]
The Survival tab appears to be having issues.  I will look into it on my end, but is there any reason why it shouldn't work on your end?

**Comment by Huh** [comment]
Ok, no data coming from the API, so I will just wait until I here that the DB is back up and running.

**Comment by gfrc11752** [comment]
Just talked with Heather, it appears Kristin must not have gotten the new data imported on Friday. She is off today, and will get the new data in the database as soon as she returns. Sorry for the delay.

**Comment by Huh** [comment]
No worries, thanks for the update.


Josh NowakUniversity of Montana

-------- Original message --------

**Comment by gfrc11752** [comment]
Should be good to go now.
