### ISSUE TITLE
Harvest Data Issues

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#65]
It appears not all of the harvest data is being properly summed in the harvest tab on the website. I have checked numerous units and the website harvest numbers are always less then they should be. I did check the raw file that is in the sequel database and that appears to be correct.

**Comment by Huh** [comment]
Hey Kevin,
Could you give me 2-3 specific examples of what the number are and what you think they should be please.  This will help my troubleshooting immensely. Josh Nowak 


     On Friday, November 6, 2015 2:21 PM, gfrc11752 <notifications@github.com> wrote:
   

 It appears not all of the harvest data is being properly summed in the harvest tab on the website. I have checked numerous units and the website harvest numbers are always less then they should be. I did check the raw file that is in the sequel database and that appears to be correct.—

**Comment by gfrc11752** [comment]
Here is the harvest data summarized for 18A from 2001 – 2014. It appears you not reporting any archery harvest on the website….

Clark Co - 18


2001

2002

2003

2004

2005

2006

2007

2008

2009

2010

2011

2012

2013

2014

ERD Harvest

1170

1354

1800

1581

1855

1585

1396

1189

922

1160

1024

944

527

303

Archery

52

70

98

118

128

83

150

159

163

203

117

147

153

126

LOL+Free

28

20

29

18

40

31

27

61

46

92

65

68

78

56

Youth+Mentor

23

33

21

21

16

8

16

51

39

49

37

56

57

67

Muzzle

17

28

27

15

11

7

18

29

27

19

18

27

9

6

SB

15

9

8

2

6

2

2

5

8

12

5

5

17

7

Total Other Harvest

135

160

183

174

201

131

213

305

283

375

242

303

314

262

Total All Harvest

1305

1514

1983

1755

2056

1716

1609

1494

1205

1535

1266

1247

841

565



































Unit

2001

2002

2003

2004

2005

2006

2007

2008

2009

2010

2011

2012

2013

2014

Brown

03A

2281

2961

2830

3116

3646

3784

3872

3660

3097

3778

2657

2079

1896

1419

Codington

05A

731

866

995

814

1071

917

992

947

646

700

616

569

461

432

Clark

18A

1305

1514

1983

1755

2056

1716

1609

1494

1205

1535

1266

1247

841

565

Day

22A

1115

1535

1428

1477

1612

1414

1180

1184

1113

1483

1106

997

753

523

Deuel

23A

643

734

872

753

963

777

709

956

666

805

629

603

511

358

Edmunds

26A

1262

1224

1628

1515

1830

1891

1688

1917

1882

2330

2054

1551

1309

1139

Faulk

28A

896

1065

1296

1325

1265

1372

1447

1491

1712

1973

1812

1912

1746

1596

Grant

29A

1013

861

921

879

1017

776

853

890

819

958

750

617

449

501

Hamlin

32A

836

803

910

907

1072

1042

1003

1187

987

1120

694

656

506

650

McPherson

47A

714

915

1018

991

1258

1229

1276

1346

1289

1556

1523

1061

823

672

Marshall

48A

1357

1461

1440

1472

1370

1256

1041

1115

972

1176

755

629

510

409

Roberts

55A

1077

1077

1132

1065

1273

1076

1009

1050

792

953

808

769

551

608

Spink

57A

1659

2025

2214

2445

2422

2431

2136

2066

1618

1749

1670

1486

1303

1062

**Comment by gfrc11752** [comment]
Some things I noticed with the harvest database for 18A.
Youth: missing years 2007, 2011, 2012 and 2013
Landowner: No harvest being reported
Archery: No harvest being reported
Mentored youth: missing 2014 data
Muzzleloader: missing 2007 - 2014 harvest
ERD: missing 2014

**Comment by Huh** [comment]
This is apparently an older error because it does not happen in the current version of the software.

Should be fixed, please verify and close this issue or comment further.

**Comment by gfrc11752** [comment]
Region 1, Unit  = BH, it appears the archery, muzzleloader, youth from 2006-2011 is not being compiled properly. The numbers are way lower then they should be.

**Comment by Huh** [comment]
What should they be?

**Comment by gfrc11752** [comment]
In your yahoo inbox

**Comment by Huh** [comment]
Currently the results compare to your reference as follows:
White-tailed Deer
Archery website is low by 39
BH Firearms website is low by 1
Muzzeloader website is high by 2
Youth website is 18 low
Mentored website is 2 high

Total difference is the website is low by 54.  I don't know if this is a difference between the datasets, but I think the site is functioning correctly.

I am going to close this because I need to change the harvest workflow at some point to add tag potential and the like as indicated by #62
