### ISSUE TITLE
Harvest Tab

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#69]
Archery harvest is not being reported correctly for all units.

**Comment by Huh** [comment]
Do you have a couple of examples?

I don't see any missing information or anything obvious.

**Comment by gfrc11752** [comment]
Example:
01A, 2013 says 39 under ARD should be 287

**Comment by gfrc11752** [comment]
2A is not reporting any harvest for ARD between 2011-2014

**Comment by gfrc11752** [comment]
2C, 2013 reporting 0 for 2013, should be 36

**Comment by Huh** [comment]
For 01A 2013 WT ARD I see 287
For 02A I see archery harvest for all years
For 2C I have 18 for both species
In the raw data 02C shows 18 for both species, the only value near 30 something is in 2014

Now I am wondering about the settings on the setup tab.  Potentially you found a way to subset that caused a failure or sorts?

**Comment by Huh** [comment]
I see it now.  If you leave the "All" in the user group things get weird.  I will fix it.

**Comment by Huh** [comment]
Pushed fix to website.  Should work now regardless of whether All is left in the subset or not.

The issue was occurring when a multiple select input took the form `c("All", "01A")`

The code now omits All form the above string when at least one value in the vector does not equal All.

**Comment by gfrc11752** [comment]
Nice, this appears to working!
