### ISSUE TITLE
Harvest tab 

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#70]
Only 4 options in the DAU drop down menu, Survival has 5, thinking we need 6. The shapefile you sent me of the DAUs only includes units.

**Comment by Huh** [comment]
I noticed that on the Harvest tab too, it may be fixed now.  
Sorry about the shapefile.  That was a dumb mistake on part. Josh Nowak 


    On Wednesday, December 2, 2015 9:03 AM, gfrc11752 <notifications@github.com> wrote:
 

 Only 4 options in the DAU drop down menu, Survival has 5, thinking we need 6. The shapefile you sent me of the DAUs only includes units. —

**Comment by Huh** [comment]
Harvest was a bug and is now fixed.

Survival, Pregnancy and Composition only shows the DAU's where there is data, if there is no data that value will not appear.  Mule Deer show this well on the survival tab.
