### ISSUE TITLE
DAU Tab

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#78]
Once the table is edited in the DAU tab, overwrite existing map to reflect those changes or create a new map that reflects those changes. Any chance  you almost have that shapefile feature almost worked out? That would be very handy along with numbering the DAUs on the map.

Thanks!

**Comment by Huh** [comment]
You are really getting creative and starting to steal my ideas.  I want numbers on the map too.  The shapefile is all but done, in fact the code is there and the spatial object is created when you click on the button.  I will get to it shortly. Josh Nowak 


    On Wednesday, December 9, 2015 12:27 PM, gfrc11752 <notifications@github.com> wrote:
 

 Once the table is edited in the DAU tab, overwrite existing map to reflect those changes or create a new map that reflects those changes. Any chance you almost have that shapefile feature almost worked out? That would be very handy along with numbering the DAUs on the map.Thanks!—

**Comment by gfrc11752** [comment]
Awesome, appreciate your hard work!

**Comment by Huh** [comment]
Added reference DAU map/plot.  

Information is shown for each unit when the user clicks on a unit.  Adding labels is rather difficult at this point, but perhaps will become easier in the future.

Shapefile download still outstanding.

**Comment by Huh** [comment]
Got a platform independent compression solution, so will implement the file download tomorrow.

The file will likely be a .tar file.

**Comment by Huh** [comment]
The new site is up, but the download is just an empty compressed file.  I will keep working on it.

**Comment by Huh** [comment]
Works now, there is extra file structure, but I will clean that up later.

**Comment by Huh** [comment]
Closing in favor of issue #85 

The shapefile download is implemented, a map has been added to display the reference DAU structure and that map can be clicked on to display the unit and DAU information for each unit.
