### ISSUE TITLE
DAU analysis

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#80]
Can we get the slider bar to go to 15 DAUs just for demonstration purposes? Hopefully we can discuss this concept more on Friday along with reviewing the statistical output from the cluster analysis and why more may not always be better.

**Comment by Huh** [comment]
Done.  You will see it when it gets pushed live. Josh Nowak 


    On Wednesday, December 9, 2015 4:09 PM, gfrc11752 <notifications@github.com> wrote:
 

 Can we get the slider bar to go to 15 DAUs just for demonstration purposes? Hopefully we can discuss this concept more on Friday along with reviewing the statistical output from the cluster analysis and why more may not always be better. —

**Comment by gfrc11752** [comment]
Thank you sir!
