### ISSUE TITLE
DAU Map 

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#86]
The DAU download map doesn't update when I change the DAU table and hit submit.

**Comment by gfrc11752** [comment]
It does re-draw when you refresh the page. Any chance you have an R script that unpacks tar files? Otherwise I need to get a moratorium approved to get 7-zip downloaded on my computer to unpack the file.

**Comment by Huh** [comment]
As for unzipping, there are a few websites that will do the unpacking for you.  Two that look promising include:

http://wobzip.org/
http://online.b1.org/online

R can unzip it for you, but you have to set some environmental variables to get it working.  The command is untar and is in the utils package, which may load by default when you open R.  Other types of compression may also be possible and I will look for OS independent solutions in the coming week that work with the windows tools.

**Comment by Huh** [comment]
I just used wobzip and it was pretty slick.  The only trick is that after you click on browse my computer and select the file there is no feedback.  Just continue to click uncompress and the page will change and show you the uncompressed files.

**Comment by gfrc11752** [comment]
That does work good. It worked best to by-pass security issues to have the files emailed and then saved in dropbox. Thanks for the website suggestion.
