### ISSUE TITLE
Harvest Data

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#9]
Where are we at with the harvest data? Will the tables work, or do we need to import the raw data?

**Comment by Huh** [comment]
The tables are what I am going to work with for now. Josh 


     On Wednesday, July 15, 2015 2:57 PM, gfrc11752 <notifications@github.com> wrote:
   

 Where are we at with the harvest data? Will the tables work, or do we need to import the raw data? —

**Comment by Huh** [comment]
I have the necessary data to get started.  We can start new issues to address estimation and uncertainty comprises/assumptions.
