### ISSUE TITLE
Survival Tab DNF = other

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#94]
Just discovered that when DNF is entered it is assigning the fate is other and it is censoring the individual. Is this problematic for the survival analysis. Should fate = other if the animal was not heard for that encounter occasion?

**Comment by Huh** [comment]
Which ID were you looking at?  Are you comparing the raw data view to your records?
If the dnf is the last entry then it sounds correct.  If the dnf occurs elsewhere in the encounter history then it may be right, but several outcomes are possible.


Josh NowakUniversity of Montana

-------- Original message --------

**Comment by Huh** [comment]
I just walked 2014111014 through the workflow for the two years it was monitored and everything was correct.  The encounter history correctly ends with a 1 despite the other entry in the fate column.  It also has an NA on 01/07/2016 that is ignored and the animal is correctly censored on the correct date.
In short, the "other" entry in the fate column is indeed a data entry error, but it does not hold any consequences for estimation.     Josh Nowak 

    On Monday, January 18, 2016 12:05 PM, joshnwk <joshnwk@yahoo.com> wrote:
 

  Which ID were you looking at?  Are you comparing the raw data view to your records?
If the dnf is the last entry then it sounds correct.  If the dnf occurs elsewhere in the encounter history then it may be right, but several outcomes are possible.


Josh NowakUniversity of Montana
<br><br>-------- Original message --------<br>From: gfrc11752 &lt;notifications@github.com&gt; <br>Date: 01/18/2016  9:25 AM  (GMT-07:00) <br>To: Huh/PopR_SDGFP &lt;PopR_SDGFP@noreply.github.com&gt; <br>Subject: [PopR_SDGFP] Survival Tab DNF = other (#94) <br><br>
Just discovered that when DNF is entered it is assigning the fate is other and it is censoring the individual. Is this problematic for the survival analysis. Should fate = other if the animal was not heard for that encounter occasion? —
Reply to this email directly or view it on GitHub.  
Just discovered that when DNF is entered it is assigning the fate is other and it is censoring the individual. Is this problematic for the survival analysis. Should fate = other if the animal was not heard for that encounter occasion?
