### ISSUE TITLE
Query sex in raw data survival tab table

### ISSUE THREAD

**Issue by gfrc11752** [Huh/PopR_SDGFP#99]
Any chance we can fix the search query for males and females in the raw data table. Right now if males is entered into the query it queries both males and females.

**Comment by Huh** [comment]
I would suggest using the sort arrow next to the column heading for the time being, but yes I will fix this shortly.

**Comment by gfrc11752** [comment]
Yep, that’s what I have been telling folks as well.

**Comment by Huh** [comment]
Changed to F and M to make sorting easier.
